---
alias: Sonos - Playlist - Absolute Radio 10s
description: Play Absolute Radio 10s on Sonos
id: Absolute_Radio_10s
trigger:
  - platform: webhook
    webhook_id: sonos_Absolute_Radio_10s
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Absolute Radio 10s"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "Absolute Radio 10s"
