---
alias: Sonos - Playlist - BBC Radio 5 live sports extra
description: Play BBC Radio 5 live sports extra on Sonos
id: BBC_Radio_5_live_sports_extra
trigger:
  - platform: webhook
    webhook_id: sonos_BBC_Radio_5_live_sports_extra
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "BBC Radio 5 live sports extra"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "BBC Radio 5 live sports extra"
