---
alias: Sonos - Playlist - Nova 96.9
description: Play Nova 96.9 on Sonos
id: Nova_96_9
trigger:
  - platform: webhook
    webhook_id: sonos_Nova_96_9
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Nova 96.9"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "Nova 96.9"
