---
alias: Sonos - Playlist - Nova 90s
description: Play Nova 90s on Sonos
id: Nova_90s
trigger:
  - platform: webhook
    webhook_id: sonos_Nova_90s
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Nova 90s"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "Nova 90s"
