---
alias: Sonos - Playlist - Nova Throwbacks
description: Play Nova Throwbacks on Sonos
id: Nova_Throwbacks
trigger:
  - platform: webhook
    webhook_id: sonos_Nova_Throwbacks
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Nova Throwbacks"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "Nova Throwbacks"
