---
alias: Sonos - Playlist - Sky Sports Radio
description: Play Sky Sports Radio on Sonos
id: Sky_Sports_Radio
trigger:
  - platform: webhook
    webhook_id: sonos_Sky_Sports_Radio
action:
  - service: media_player.select_source
    data:
      entity_id: media_player.office_sonos
      source: "Sky Sports Radio"
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "Sky Sports Radio"
