handle_update_channels:
  name: update_channels
  description: Force update Guide file
  fields:
    entry_id:
      name: config_entry
      description: The ID of the config_entry to update
      required: true
      selector:
        config_entry:
          integration: "epg"


search_program:
  name: Search EPG Program
  description: >
    Searches for a program title across configured EPG channels and returns matching schedules directly in the response.
  fields:
    title:
      name: Title
      description: The program title (or part of it) to search for (case-insensitive).
      required: true
      example: "News at Ten"
      selector:
        text:
    channel_name:
      name: Channel Name
      description: (Optional) Filter results to only this specific channel name (exact match, case-sensitive from guide data).
      required: false
      example: "BBC One HD"
      selector:
        text:
    date_filter:
      name: Date Filter
      description: (Optional) Filter results by date. 'all_future' includes today and onwards.
      required: false
      default: 'any'
      example: 'today'
      selector:
        select:
          options:
            - label: "Any Time"
              value: "any"
            - label: "Today Only"
              value: "today"
            - label: "Tomorrow Only"
              value: "tomorrow"
    entry_id:
      name: Config Entry ID
      description: (Optional) The configuration entry ID to search within. If omitted, searches across all configured EPG entries.
      required: false
      example: "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4"
      selector:
        config_entry:
          integration: epg





