---
# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - "README.md"
name: TOC Generator
jobs:
  generateTOC:
    name: Generate TOC
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v4.3.1
        with:
          TOC_TITLE: "Details"
          FOLDING: true
