# Start of the dwains theme ui-lovelace.yaml
# Don't change anything below this section, only if you know what you are doing

# Do you have any custom resources? Go to the folder dwains-theme/resources/, 
# if you don't have the file custom_resources.yaml then rename the file custom_resources-sample.yaml
# to custom_resources.yaml and place your resources in the file custom_resources.yaml!

# Loading all necessary components for dwains theme...
# Custom Header with some custom configuration (https://github.com/maykar/custom-header)
custom_header:
  !include dwains-theme/plugins/custom_header/configuration.yaml
      
# Button Card Templates folder (https://github.com/custom-cards/button-card#Configuration-Templates)
# These are the templates used to avoid too much duplicate code.      
button_card_templates:
  !include_dir_merge_named dwains-theme/plugins/button-cards-templates        
 
# Start of main lovelace theme 
background: var(--background-image)
views:
  !include_dir_merge_list dwains-theme/views/main/
# End of the dwains theme ui-lovelace.yaml part
######