---
sensor:
  - platform: sonarr
    api_key: !secret sonarr_apikey
    host: !secret sonarr_host
    port: !secret sonarr_port
    monitored_conditions:
      - upcoming
      - queue
      - series
      - wanted
      - status
      - commands
    days: 720
