---
alias: "[TVGuide] XMLTV Download"
description: "[TVGuide] XMLTV Download"
trigger:
  - platform: homeassistant
    event: start
    id: startup
  - platform: time_pattern
    hours: /2
action:
  - if: "{{ trigger.id == 'startup' }}"
    then:
      - delay: 300
  - service: pyscript.download_xmltv
    data:
      url: https://i.mjh.nz/Optus/epg.xml
      statussensor: sensor.tvguide_xmltv_status_optussport
      filename: optus_sport.xml
      sensorname: Optus Sport
