---
sensor:
  - platform: rest
    timeout: 60
    scan_interval: 3600
    force_update: true
    method: GET
    headers:
      User-Agent: 'Home Assistant REST sensor'
    resource: >-
      'https://services1.arcgis.com/0MSEUqKaxRlEPj5g/arcgis/rest/services/ncov_cases/FeatureServer/1/query?f=json&where=(Confirmed%20%3E%200)%20AND%20(Province_State%3D%27New South Wales%27)&returnGeometry=false&spatialRel=esriSpatialRelIntersects&outFields=*&orderByFields=Confirmed%20desc%2CCountry_Region%20asc%2CProvince_State%20asc&outSR=102100&resultOffset=0&resultRecordCount=250&cacheHint=true'
    name: 'Coronavirus NSW'
    value_template: >-
      {{ value_json.features[0].attributes.Confirmed }}
    json_attributes_path: '$.features[0].attributes'
    json_attributes:
      - Confirmed
      - Deaths
      - Recovered
      - Last_Update
    unit_of_measurement: 'People'
