---
homeassistant:
  customize:
    sensor.fuelcheck_caltex_tamworth_orana_p98:
      friendly_name: Caltex Vortex98 (WhiteSt)
      icon: mdi:fuel

    sensor.fuelcheck_bp_tamworth_p98:
      friendly_name: BP Ultimate98 (Viaduct)
      icon: mdi:fuel

    sensor.fuelcheck_bp_nemingha_p98:
      friendly_name: BP Ultimate98 (Nemingha)
      icon: mdi:fuel

    sensor.fuelcheck_bp_tamworth_p98_2:
      friendly_name: BP Ultimate98 (GoonooGoonooRd)
      icon: mdi:fuel

    sensor.fuelcheck_caltex_tamworth_p98:
      friendly_name: Caltex Vortex98 (GunnedahRd)
      icon: mdi:fuel

    sensor.fuelcheck_caltex_woolworths_tamworth_p98:
      friendly_name: Caltex Vortex98 (BridgeSt)
      icon: mdi:fuel

sensor:
  - platform: nsw_fuel_station
    entity_namespace: fuelcheck
    fuel_types: P98
    station_id: 1145

  - platform: nsw_fuel_station
    entity_namespace: fuelcheck
    fuel_types: P98
    station_id: 16921

  - platform: nsw_fuel_station
    entity_namespace: fuelcheck
    fuel_types: P98
    station_id: 573

  - platform: nsw_fuel_station
    entity_namespace: fuelcheck
    fuel_types: P98
    station_id: 2449

  - platform: nsw_fuel_station
    entity_namespace: fuelcheck
    fuel_types: P98
    station_id: 916

  - platform: nsw_fuel_station
    entity_namespace: fuelcheck
    fuel_types: P98
    station_id: 1141
