---
sensor:
  - platform: launch_library

  - platform: rest
    scan_interval: 1800
    resource: https://launchlibrary.net/1.2.2/launch/next/10
    name: launch window
    value_template: >-
      {%- for launch in value_json.launches %}
        {% if launch.location.id == 16 or launch.location.id == 17 %}
          {% if strptime(launch.isostart, '%Y%m%dT%H%M%SZ').strftime('%Y-%m-%d') == now().strftime('%Y-%m-%d') %}
            {% set utc_offset_string = now().strftime('%z') %}
            {% set utc_offset_direction = utc_offset_string[:1] %}
            {% set utc_offset_hours = now().strftime('%z')[-4:] %}
            {% set utc_offset_seconds = (utc_offset_hours| int /100) * 60 * 60 %}
            {% if utc_offset_direction == '-' %}
             {{ launch.wsstamp - utc_offset_seconds}}
            {% else %}
              {{ launch.wsstamp + utc_offset_seconds}}
            {% endif %}
          {% endif %}
        {% endif %}
      {% endfor %}
