---
homeassistant:
  customize:
    sensor.spacex_next_rocket:
      icon: mdi:rocket
    sensor.spacex_next_launch_day:
      icon: mdi:calendar
    sensor.spacex_next_launch_time:
      icon: mdi:clock-outline
    sensor.spacex_next_launch_site:
      icon: mdi:map-marker-radius
    sensor.spacex_next_mission_name:
      icon: mdi:information-outline

sensor:
  - platform: rest
    name: SpaceX
    json_attributes:
      - flight_number
      - mission_name
      - launch_site
      - rocket
      - details
    value_template: '{{ value_json["launch_date_unix"] }}'
    resource: 'https://api.spacexdata.com/v2/launches/next'
  - platform: template
    sensors:
      spacex_next_launch_day:
        friendly_name: 'Next Launch Day'
        value_template: '{{ states.sensor.spacex.state | int | timestamp_custom("%d.%m.%Y")}}'
        entity_id: sensor.spacex
      spacex_next_launch_time:
        friendly_name: 'Next Launch Time'
        value_template: '{{ states.sensor.spacex.state | int | timestamp_custom("%H:%M")}}'
        unit_of_measurement: 'h'
        entity_id: sensor.spacex
      spacex_next_rocket:
        friendly_name: 'Next Rocket'
        value_template: '{{ states.sensor.spacex.attributes["rocket"]["rocket_name"] }}'
        entity_id: sensor.spacex
      spacex_next_launch_site:
        friendly_name: 'Next Launch Site'
        value_template: '{{ states.sensor.spacex.attributes["launch_site"]["site_name"] }}'
        entity_id: sensor.spacex
      spacex_next_mission_name:
        friendly_name: 'Next Mission Name'
        value_template: '{{ states.sensor.spacex.attributes["mission_name"] }}'
        entity_id: sensor.spacex
