---
homeassistant:
  customize:
    sensor.ha_db_size:
      icon: mdi:database
    sensor.ha_db_events:
      icon: mdi:database
    sensor.ha_db_states:
      icon: mdi:database

sensor:
  - platform: sql
    db_url: !secret mariadb_connection
    scan_interval: 120
    queries:
      - name: HA DB Size
        query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / 1024 / 1024, 1) "value" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema;'
        column: 'value'
        unit_of_measurement: Mb
      - name: HA DB Events
        query: 'SELECT count(*) number_events, max(created) max_time, min(created) min_time FROM events;'
        column: number_events
        unit_of_measurement: rows
      - name: HA DB States
        query: 'SELECT count(*) number_states, max(created) max_time, min(created) min_time FROM states;'
        column: number_states
        unit_of_measurement: rows
