---
binary_sensor:
  - platform: tod
    name: Early Morning
    after: sunrise
    after_offset: '-02:00'
    before: '07:00'

  - platform: tod
    name: Late Morning
    after: '10:00'
    before: '12:00'

  - platform: tod
    name: Night
    after: sunset
    before: sunrise

  - platform: tod
    name: Day
    after: sunrise
    before: sunset

  - platform: tod
    name: Work
    after: '07:00'
    before: '17:00'

sensor:
  - platform: template
    sensors:
      day_phase:
        friendly_name: 'Day Phase'
        value_template: >
          {% if now() > now().replace(hour=5).replace(minute=0).replace(second=0) and
              now() < now().replace(hour=9).replace(minute=0).replace(second=0) %}
              Morning
          {% elif states.sun.sun.state == "above_horizon" %}
              Day
          {% elif now() < now().replace(hour=22).replace(minute=0).replace(second=0) and
              now() > now().replace(hour=9).replace(minute=0).replace(second=0) %}
              Evening
          {% else %}
              Night
          {% endif %}
