""" Clear all sensor values """


async def async_clear_values() -> dict:
    """Clear all state attributes"""
    new_values = {}

    # Reset values
    new_values = {
        "sport": None,
        "sport_path": None,
        "league": None,
        "league_path": None,
        "league_logo": None,
        "season": None,
        "team_abbr": None,
        "opponent_abbr": None,
        "event_name": None,
        "event_url": None,
        "date": None,
        "kickoff_in": None,
        "series_summary": None,
        "venue": None,
        "location": None,
        "tv_network": None,
        "odds": None,
        "overunder": None,
        "team_name": None,
        "team_long_name": None,
        "team_id": None,
        "team_record": None,
        "team_rank": None,
        "team_conference_id": None,
        "team_homeaway": None,
        "team_logo": None,
        "team_url": None,
        "team_colors": None,
        "team_score": None,
        "team_win_probability": None,
        "team_winner": None,
        "team_timeouts": None,
        "opponent_name": None,
        "opponent_long_name": None,
        "opponent_id": None,
        "opponent_record": None,
        "opponent_rank": None,
        "opponent_conference_id": None,
        "opponent_homeaway": None,
        "opponent_logo": None,
        "opponent_url": None,
        "opponent_colors": None,
        "opponent_score": None,
        "opponent_win_probability": None,
        "opponent_winner": None,
        "opponent_timeouts": None,
        "quarter": None,
        "clock": None,
        "possession": None,
        "last_play": None,
        "down_distance_text": None,
        "outs": None,
        "balls": None,
        "strikes": None,
        "on_first": None,
        "on_second": None,
        "on_third": None,
        "team_shots_on_target": None,
        "team_total_shots": None,
        "opponent_shots_on_target": None,
        "opponent_total_shots": None,
        "team_sets_won": None,
        "opponent_sets_won": None,
        "last_update": None,
        "api_message": None,
        "api_url": None,
        "private_fast_refresh": False,
    }

    return new_values
