---
netatmo:
  client_id: !secret netatmo_apikey
  client_secret: !secret netatmo_secretkey
#   username: !secret netatmo_username
#   password: !secret netatmo_password
#   discovery: false

sensor:
  # - platform: netatmo
  #   modules:
  #     - Indoor
  #     - Outdoor
  #     - Rain

  # - platform: netatmo
  #   areas:
  #     - lat_ne: -31.008
  #       lon_ne: 151.122
  #       lat_sw: -31.262
  #       lon_sw: 150.733
  #       name: Netatmo Public

  - platform: statistics
    name: today_temp_netatmoindoor
    sampling_size: 150
    entity_id: sensor.netatmo_brisbane_street_indoor_temperature
    max_age:
      hours: 24

  - platform: statistics
    name: today_temp_netatmooutdoor
    sampling_size: 150
    entity_id: sensor.netatmo_brisbane_street_outdoor_temperature
    max_age:
      hours: 24

  - platform: template
    sensors:
      netatmoindoor_min_temp:
        friendly_name: 'Indoor Min Temp'
        value_template: "{{ states.sensor.today_temp_netatmoindoor.attributes['min_value']}}"
        icon_template: mdi:thermometer-chevron-down
        unit_of_measurement: '°C'
      netatmoindoor_max_temp:
        friendly_name: 'Indoor Max Temp'
        value_template: "{{ states.sensor.today_temp_netatmoindoor.attributes['max_value']}}"
        icon_template: mdi:thermometer-chevron-up
        unit_of_measurement: '°C'
      netatmoindoor_change_temp:
        friendly_name: 'Indoor Temp Change (Last 24hrs)'
        value_template: "{{ states.sensor.today_temp_netatmoindoor.attributes['change']}}"
        icon_template: mdi:thermometer-lines
        unit_of_measurement: '°C'
      netatmooutdoor_min_temp:
        friendly_name: 'Outdoor Min Temp'
        value_template: "{{ states.sensor.today_temp_netatmooutdoor.attributes['min_value']}}"
        icon_template: mdi:thermometer-chevron-down
        unit_of_measurement: '°C'
      netatmooutdoor_max_temp:
        friendly_name: 'Outdoor Max Temp'
        value_template: "{{ states.sensor.today_temp_netatmooutdoor.attributes['max_value']}}"
        icon_template: mdi:thermometer-chevron-up
        unit_of_measurement: '°C'
      netatmooutdoor_change_temp:
        friendly_name: 'Outdoor Temp Change (Last 24hrs)'
        value_template: "{{ states.sensor.today_temp_netatmoindoor.attributes['change']}}"
        icon_template: mdi:thermometer-lines
        unit_of_measurement: '°C'
