---
sun:
  elevation: !secret zone_home_elevation

sensor:
  - platform: template
    sensors:
      sun_state_day:
        friendly_name: Sun State
        value_template: >-
          {% if is_state('sun.sun', 'above_horizon') %}
            Day
          {% else %}
            Night
          {% endif %}
        icon_template: >-
          {% if is_state('sun.sun', 'above_horizon') %}
            mdi:weather-sunny
          {% else %}
            mdi:weather-night
          {% endif %}

      sun_nextdawn:
        friendly_name: Next Dawn
        value_template: "{{ as_timestamp(states.sun.sun.attributes.next_dawn) | timestamp_custom('%a %H:%M') }}"
        icon_template: mdi:weather-sunset-up

      sun_nextdusk:
        friendly_name: Next Dusk
        value_template: "{{ as_timestamp(states.sun.sun.attributes.next_dusk) | timestamp_custom('%a %H:%M') }}"
        icon_template: mdi:weather-sunset-down

      sun_nextmidnight:
        friendly_name: Next Midnight
        value_template: "{{ as_timestamp(states.sun.sun.attributes.next_midnight) | timestamp_custom('%a %H:%M') }}"
        icon_template: mdi:weather-night

      sun_nextnoon:
        friendly_name: Next Noon
        value_template: "{{ as_timestamp(states.sun.sun.attributes.next_noon) | timestamp_custom('%a %H:%M') }}"
        icon_template: mdi:weather-sunny

      sun_nextrising:
        friendly_name: Next Rising
        value_template: "{{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom('%a %H:%M') }}"
        icon_template: mdi:weather-sunset-up

      sun_nextsetting:
        friendly_name: Next Setting
        value_template: "{{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom('%a %H:%M') }}"
        icon_template: mdi:weather-sunset-down

      sun_solarangle:
        friendly_name: "Sun Angle"
        unit_of_measurement: "°"
        value_template: "{{ '%+.1f'|format(state_attr('sun.sun', 'elevation')) }}"
        icon_template: mdi:weather-sunny

      sun_state:
        friendly_name: Sun
        icon_template: >-
          {% if is_state('sun.sun', 'above_horizon') %}
            mdi:weather-sunny
          {% else %}
            mdi:weather-night
          {% endif %}
        value_template: >-
          {% if is_state('sun.sun', 'above_horizon') %}
            sets at {% set timestamp = as_timestamp(state_attr('sun.sun', 'next_setting')) | timestamp_custom('%H:%M') %} {{ timestamp.lstrip('0') }}
          {% else %}
            rises at {% set timestamp = as_timestamp(state_attr('sun.sun', 'next_rising')) | timestamp_custom('%H:%M') %} {{ timestamp.lstrip('0') }}
          {% endif %}

      sun_state_friendly:
        friendly_name: Sun
        icon_template: >-
          {% if is_state('sun.sun', 'above_horizon') %}
            mdi:weather-sunny
          {% else %}
            mdi:weather-night
          {% endif %}
        value_template: >-
          {% set current = as_timestamp(strptime(states('sensor.date_time'), '%Y-%m-%d, %H:%M')) %}
          {% set dusk = as_timestamp(state_attr('sun.sun', 'next_dusk')) %}
          {% if current <= dusk %}
            {# output example "will set at around 8." #}
            {# output example "will set at around a quarter past 8." #}
            {# output example "will set at around 8 and a half." #}
            {# output example "will set at around a quarter to 9." #}
            {# output example "will set in a few minutes." #}
            {# output example "is setting." #}
            {% set setting = as_timestamp(state_attr('sun.sun', 'next_setting')) %}
            {% if current >= setting %}
              is setting
            {% elif (setting - current) <= 60*30 %}
              will set in a few minutes
            {% else %}
              {% set hour = setting|timestamp_custom('%H') | int %}
              {% set minute = setting|timestamp_custom('%M') | int %}
              {% set minute_friendly = '' %}
              {% set half = false %}
              {% if minute >= 10 and minute <= 20 %}
                {% set minute_friendly = 'a quarter past ' %}
              {% elif minute > 20 and minute < 40 %}
                {% set half = true %}
              {% elif minute >= 40 and minute <= 50 %}
                {% set minute_friendly = 'a quarter to ' %}
                {% set hour = hour + 1 %}
              {% elif minute > 50 %}
                {% set hour = hour + 1 %}
              {% endif %}
              {% if hour >= 24 %}
                {% set hour = hour - 24 %}
              {% endif %}
              {% if hour == 0 %}
                {% set hour_friendly = 'midnight' %}
              {% elif hour == 12 %}
                {% set hour_friendly = 'noon' %}
              {% elif hour > 12 %}
                {% set hour_friendly = hour - 12 %}
              {% else %}
                {% set hour_friendly = hour %}
              {% endif %}
              {% if half %}
                will set at around {{ hour_friendly }} and a half
              {% else %}
                will set at around {{ minute_friendly }}{{ hour_friendly }}
              {% endif %}
            {% endif %}
          {% else %}
            {# output example "will rise in about 7 hours." #}
            {# output example "will rise in about 7 and a half hours." #}
            {# output example "will rise in a few minutes." #}
            {# output example "is rising." #}
            {% set dawn = as_timestamp(state_attr('sun.sun', 'next_dawn')) %}
            {% set rising = as_timestamp(state_attr('sun.sun', 'next_rising')) %}
            {% set diff = ((rising - current) / 60 / 60) %}
            {% set hour = diff | int %}
            {% set minute = (diff - hour) | round(2) %}
            {% if hour %}
              {% if minute > 0.66 %}
                {% set hour = hour + 1 %}
              {% elif minute > 0.33 %}
                {% set minute_friendly = ' and a half' %}
              {% endif %}
              will rise in about {{hour}}{{ minute_friendly }} hour{% if hour > 0 %}s{% endif %}
            {% elif (rising - dawn) < 0%}
              is rising
            {% else %}
              will rise in a few minutes
            {% endif %}
          {% endif %}
