---
homeassistant:
  customize_glob:
    "geo_location.wwlln_*":
      icon: mdi:flash

wwlln:
  radius: 50

sensor:
  - platform: template
    sensors:
      lightning_near_me:
        entity_id: sensor.date_time
        friendly_name: 'Lightning Strikes Near Me'
        icon_template: mdi:flash
        value_template: |
          {% for state in states
          if ('lightning_strike' in state.entity_id and state.domain in ['geo_location']) -%}
          {% if loop.last -%}
          {{ loop.index }}
          {%- endif %}
          {% else %}
          0
          {%- endfor %}
