---
alias: "[Sonos Favourites] Play Double J Sydney"
description: Play Double J Sydney on Sonos
id: sonos_favourites_play_double_j_sydney
trigger:
  - platform: webhook
    webhook_id: sonos_double_j_sydney
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: script.toggle
    target:
      entity_id: script.sonos_favourites_double_j_sydney
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "Double J Sydney"
