---
id: "pyscript_getdata_daily"
alias: "PyScript, GetData: Daily"
description: "PyScript, GetData: Daily"
trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    hours: "/12"
condition: []
action:
  - service: pyscript.getdata_f1driverstandings
    data:
      icon: "mdi:racing-helmet"
  - service: pyscript.getdata_f1constructorstandings
    data:
      icon: "mdi:racing-helmet"
  - service: pyscript.getdata_afldraw
    data:
      icon: "mdi:football-australian"
  - service: pyscript.getdata_aflladder
    data:
      icon: "mdi:football-australian"
  - service: pyscript.getdata_nrldraw
    data:
      icon: "mdi:football"
  - service: pyscript.getdata_nrlladder
    data:
      icon: "mdi:football"
  - service: pyscript.getdata_untappd
    data:
      entity_id: sensor.untappd_beers_date
      user: bacco007
      sort: date

  - service: pyscript.getdata_untappd
    data:
      entity_id: sensor.untappd_beers_most
      user: bacco007
      sort: checkin

  - service: pyscript.getdata_untappd
    data:
      entity_id: sensor.untappd_beers_ratehigh
      user: bacco007
      sort: highest_rated_you

  - service: pyscript.getdata_untappd
    data:
      entity_id: sensor.untappd_beers_ratelow
      user: bacco007
      sort: lowest_rated_you

mode: single
