---
id: logger_setdefaultlevel
alias: Logger - Set Default Level
trigger:
  - platform: state
    entity_id: input_select.log_level
action:
  service: logger.set_default_level
  data_template:
    level: "{{ states('input_select.log_level') }}"
