---
alias: Webhook - Office Lamp & Sonos Off
description: ""
initial_state: true
trigger:
  - platform: webhook
    webhook_id: office_lampsonos_off
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: "LightsSonosActionOver"
action:
  - entity_id: light.office_lamp
    service: light.turn_off
    data: {}
  - data: {}
    entity_id: media_player.office_sonos
    service: media_player.media_stop
