{
 "title": "Weather",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "BOM Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"value\") AS \"Maximum Temp\", min(\"value\") AS \"Minimum Temp\" FROM \"homeassistant\".\"autogen\".\"°C\" WHERE time > now() - 365d AND (\"entity_id\"='bom_tamworth_air_temp_c' OR \"entity_id\"='bom_air_temp_c') GROUP BY time(1d) FILL(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "BOM Rainfall",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "lengthmm" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"value\") AS \"Rainfall\" FROM \"homeassistant\".\"autogen\".\"mm\" WHERE time > now() - 365d AND (\"entity_id\"='bom_rain_today' OR \"entity_id\"='bom_tamworth_rain_today') GROUP BY time(1d) FILL(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Home Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"value\") AS \"Maximum Temp\", min(\"value\") AS \"Minimum Temp\" FROM \"homeassistant\".\"autogen\".\"°C\" WHERE time > now() - 365d AND (\"entity_id\"='netatmo_brisbane_street_outdoor_temperature' OR \"entity_id\"='netatmo_outdoor_temperature') GROUP BY time(1d) FILL(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Home Rainfall",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "lengthmm" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"value\") AS \"Rainfall\" FROM \"homeassistant\".\"autogen\".\"mm\" WHERE time > now() - 365d AND (\"entity_id\"='netatmo_rain_sum_rain_24' OR \"entity_id\"='netatmo_brisbane_street_rain_sum_rain_24') GROUP BY time(1d) FILL(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}