{
 "title": "Play",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "Download Speed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT min(\"value\") AS \"Min Download\", max(\"value\") AS \"Max Download\", mean(\"value\") as \"Avg Download\" FROM \"homeassistant\".\"autogen\".\"Mbit/s\" WHERE time > now() - 365d AND \"entity_id\"='speedtest_download' GROUP BY time(1d) FILL(null) TZ('Australia/Sydney')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT min(\"value\") AS \"Min Upload\", max(\"value\") AS \"Max Upload\", mean(\"value\") As \"Avg Upload\" FROM \"homeassistant\".\"autogen\".\"Mbit/s\" WHERE time > now() - 365d AND \"entity_id\"='speedtest_upload' GROUP BY time(1d) FILL(null) TZ('Australia/Sydney')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UniFi - Connected Devices",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"value\") AS \"Max\", min(\"value\") as \"Min\", mean(\"value\") as \"Avg\" FROM \"homeassistant\".\"autogen\".\"Users\" WHERE time > now() - 365d AND (\"entity_id\"='unifi_gateway_wlan_user' OR \"entity_id\"='unifi_gateway_lan_user') GROUP BY time(1d) FILL(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Air Quality Index",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "none", "label": "AQI" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") AS \"Average AQI\" FROM \"homeassistant\".\"autogen\".\"AQI\" WHERE time > now() - 365d AND \"entity_id\"='waqi_tamworth_north_west_slopes_australia' GROUP BY time(1h) FILL(linear) TZ('Australia/Sydney')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "InfluxDB Rate of Change",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT derivative(mean(\"value\"),1h)*100 AS \"value\" FROM \"homeassistant\".\"autogen\".\"Mb\" WHERE time > now() - 365d AND \"entity_id\"='influxdb_size' GROUP BY time(1h) FILL(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "MariaDB Rate of Change",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT derivative(mean(\"value\"),1h)*100 AS \"value\" FROM \"homeassistant\".\"autogen\".\"Mb\" WHERE time > now() - 365d AND \"entity_id\"='ha_db_size' GROUP BY time(1h) FILL(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}