---
homeassistant:
  customize:
    sensor.hasupervisor_addon_adb:
      friendly_name: 'ADB - Android Debug Bridge'
      icon: 'mdi:home-assistant'

sensor:
  - platform: rest
    resource: http://192.168.1.62:8123/api/hassio/addons/a0d7b954_adb/info
    name: hasupervisor_addon_adb
    value_template: '{{ value_json.data.state }}'
    scan_interval: 60
    json_attributes_path: '$.data'
    json_attributes:
      - name
      - available
      - version
      - last_version
    headers:
      Content-Type: application/json
      Authorization: !secret ha_api_llat
      User-Agent: Home Assistant REST sensor

switch:
  - platform: template
    switches:
      hasupervisor_addon_adb:
        value_template: "{{ is_state('sensor.hasupervisor_addon_adb', 'started') }}"
        turn_on:
          service: hassio.addon_start
          data:
            addon: a0d7b954_adb
        turn_off:
          service: hassio.addon_stop
          data:
            addon: a0d7b954_adb
