# https://dwainscheeren.github.io/lovelace-dwains-theme/configuration/more_page.html

more_page:
  addons:
    - name: Coronavirus
      icon: fas:disease
      path: 'dwains-theme/addons/more_page/coronavirus/page.yaml'
    - name: IoT & Smarthome Network Status
      icon: fal:chart-network
      path: 'dwains-theme/addons/more_page/net-status/page.yaml'
    - name: National Electricity Market (NSW)
      icon: mdi:transmission-tower
      path: 'dwains-theme/addons/more_page/opennem/page.yaml'
    - name: Netatmo Weather Station
      icon: fal:windsock
      path: 'dwains-theme/addons/more_page/netatmo/page.yaml'
    - name: Pi-Hole
      icon: mdi:pi-hole
      path: 'dwains-theme/addons/more_page/pi-hole/page.yaml'
    - name: Synology NAS
      icon: mdi:nas
      path: 'dwains-theme/addons/more_page/synology/page.yaml'
    - name: Ubiquiti UniFi
      icon: fal:router
      path: 'dwains-theme/addons/more_page/ubiquiti/unifi.yaml'
    - name: Upcoming Sport
      icon: mdi:football-australian
      path: 'dwains-theme/addons/more_page/sports/page.yaml'
    - name: Weather
      icon: fal:cloud-sun-rain
      path: 'dwains-theme/addons/more_page/weather/page.yaml'
#     - name: Hello more page
#       icon: fas:chart-area
#       path: 'dwains-theme/addons/more_page/hello-more-page/page.yaml'
#       data:
#         some_data: 'This is some data parsed.'
#         some_other_data: 'and some other data.'