# https://dwainscheeren.github.io/lovelace-dwains-theme/configuration/rooms.html

rooms:
  - name: Bedroom
    icon: mdi:bed-king-outline
    light: light.lamp
    climate: climate.bedroom
    temperature: sensor.zha_bedroom_temperature
    humidity: sensor.zha_bedroom_humidity
    pressure: sensor.zha_bedroom_pressure
    media_player: group.bedroom_media
    device: group.bedroom_switch
    page_entities:
      entities:
        - entity: sensor.bedroom_iaq_index
        - entity: sensor.xiaomibedroom_max_temp
        - entity: sensor.xiaomibedroom_min_temp

  - name: Lounge
    icon: mdi:television-classic
    media_player: group.lounge_media
    temperature: sensor.netatmo_brisbane_street_indoor_temperature
    humidity: sensor.netatmo_brisbane_street_indoor_humidity
    pressure: sensor.netatmo_brisbane_street_indoor_pressure
    page_entities:
      entities:
        - entity: sensor.lounge_iaq_index
        - entity: sensor.netatmo_brisbane_street_indoor_co2
        - entity: sensor.netatmo_brisbane_street_indoor_noise

  - name: Office
    icon: mdi:briefcase
    temperature: sensor.zha_office_temperature
    humidity: sensor.zha_office_humidity
    pressure: sensor.zha_office_pressure
    media_player: group.office_media
    motion: binary_sensor.zha_office_motion
    light: light.zha_office_light
    page_entities:
      entities:
        - entity: sensor.zha_office_illuminance
        - entity: sensor.office_iaq_index
    addons:
      - name: Sonos
        icon: fal:speaker
        path: 'dwains-theme/addons/rooms/office/sonos/page.yaml'
        button_path: 'dwains-theme/addons/rooms/office/sonos/button.yaml'
        data:
          entity: binary_sensor.networkstatus_sonos
  - name: Spare Room
    icon: mdi:bed-empty
    light: light.zha_spare_light
  - name: Laundry
    icon: mdi:washing-machine
    temperature: sensor.zha_laundry_temperature
    motion: binary_sensor.zha_laundry_motion
    door: binary_sensor.zha_laundry_door
    page_entities:
      entities:
        - entity: sensor.washer
        - entity: binary_sensor.washer_error_state
        - entity: binary_sensor.washer_wash_completed

  - name: Outside
    icon: mdi:home-export-outline
    temperature: sensor.netatmo_brisbane_street_outdoor_temperature
    humidity: sensor.netatmo_brisbane_street_outdoor_humidity
    page_entities:
      entities:
        - entity: sensor.netatmo_brisbane_street_rain_sum_rain_24

  - name: Garage
    icon: mdi:garage
    page_entities:
      entities:
        - entity: sensor.fuelcheck_bp_tamworth_p98
        - entity: sensor.fuelcheck_bp_nemingha_p98
        - entity: sensor.fuelcheck_bp_tamworth_p98_2
        - entity: sensor.fuelcheck_caltex_tamworth_orana_p98
        - entity: sensor.fuelcheck_caltex_tamworth_p98
        - entity: sensor.fuelcheck_caltex_woolworths_tamworth_p98

  - name: Server Rack
    icon: mdi:server-network
    device: group.serverrack_device
    page_entities:
      entities:
        - entity: sensor.pvetbsh_uptime
        - entity: sensor.tbsh01_uptime
        - entity: sensor.thecube2_uptime
        - entity: sensor.vmtbsh01_uptime
        - entity: sensor.vmtbsh02_uptime
        - entity: sensor.ufo_uptime
        - entity: sensor.usg_uptime
        - entity: sensor.piserv_uptime
        - entity: sensor.hateful8_uptime
    addons:
      - name: Synology NAS
        icon: mdi:nas
        path: 'dwains-theme/addons/more_page/synology/page.yaml'
        button_path: 'dwains-theme/addons/rooms/hello-room/button.yaml'
        data:
          entity: binary_sensor.networkstatus_nas_thecube2
      - name: Ubiquiti UniFi
        icon: mdi:router-wireless
        path: 'dwains-theme/addons/more_page/ubiquiti/unifi.yaml'
        button_path: 'dwains-theme/addons/rooms/hello-room/button.yaml'
        data:
          entity: binary_sensor.tbsh01_ha_dockermon_unifi

  - name: Tamworth
    icon: mdi:road-variant
    temperature: sensor.bom_tamworth_air_temp_c
    humidity: sensor.bom_tamworth_relative_humidity
    pressure: sensor.bom_tamworth_pressure_mb
    page_entities:
      entities:
        - entity: sensor.bom_max_temp
        - entity: sensor.bom_min_temp
