apple_tv_mrp_authenticate:
  description: Start AirPlay device authentication.
  fields:
    entity_id: {description: Name(s) of entities to authenticate with., example: media_player.apple_tv}
apple_tv_mrp_scan: {description: Scan for Apple TV devices.}
