---
compact_mode: true
background: "var(--custom_cch_background)"
voice_hide: true
hide_help: true
hide_config: true
chevrons: false
active_tab_color: "var(--accent-color)"
notification_dot_color: "var(--accent-color)"
all_tabs_color: "var(--sidebar-icon-color)"
all_buttons_color: "var(--sidebar-icon-color)"
