---
view_css: 'padding-top: 84px !important'
compact_mode: true
hide_header: false
locale: en-gb
split_mode: false
shadow: true
footer_mode: false
background: "rgba(69, 74, 83, 1)"
voice_hide: true
hide_help: true
hide_config: true
chevrons: false
active_tab_color: "var(--accent-color)"
notification_dot_color: "var(--accent-color)"
all_tabs_color: "var(--sidebar-icon-color)"
all_buttons_color: "var(--sidebar-icon-color)"
tabs_color:
  # Sun
  6: "{% if states.binary_sensor.protection_window.state == 'on' %}yellow{% else %}var(--sidebar-icon-color){% endif %}"
  # Fire
  9: "{% if states.binary_sensor.fire_ban_today.state == 'on' %}yellow{% else %}var(--sidebar-icon-color){% endif %}"
  # HA
  14: "{% if is_state('sensor.hacs', '0') %}var(--sidebar-icon-color){% else %}yellow{% endif %}"
