---
alias: "[Notifications] Updates Available"
id: notifications_updates_available
mode: single
trigger:
  - platform: time_pattern
    hours: /3
  - platform: state
    entity_id:
      - update.home_assistant_core_update
    to: "on"
  - platform: state
    entity_id:
      - update.home_assistant_operating_system_update
    to: "on"
  - platform: state
    entity_id:
      - update.hacs_update
    to: "on"
condition:
  - condition: time
    after: "06:00:00"
    before: "20:00:00"
action:
  - service: notify.alert
    data:
      title: Updates Available
      message: &update-message >-
        {%- for upd in states.update %}
        {%- set ignore = ['unknown', 'unavailable', 'none', '']  %}
        {%- if upd.state == 'on' and
              state_attr(upd.entity_id, 'latest_version') is defined and
              state_attr(upd.entity_id, 'installed_version') is defined and
              state_attr(upd.entity_id, 'latest_version') is not in ignore %}
        {%- if is_state_attr(upd.entity_id, 'display_icon', 'mdi:docker') %}
        {%- set name = state_attr(upd.entity_id, 'display_name') + " (" + state_attr(upd.entity_id, 'watcher') + ")" %}
        {%- else %}
        {%- set name = iif(state_attr(upd.entity_id, 'title') == "null", state_attr(upd.entity_id, 'title'), state_attr(upd.entity_id, 'friendly_name')) %}
        {%- endif %}
        - {{name}}: {{state_attr(upd.entity_id, 'installed_version')}} -> {{state_attr(upd.entity_id, 'latest_version')}}
        {% endif %}
        {%- endfor %}
      data:
        tag: updates_available
        notification_id: updates_available
        push:
          badge: 1
          sound: none
          interruption-level: time-sensitive
        presentation_options:
          - alert
          - badge
        group: alerts
        actions:
          - title: "Pause Alert"
            action: pause_alert_updates_available
  - service: persistent_notification.create
    data:
      notification_id: update-alert
      title: Updates Available
      message: *update-message
