---
alias: "[Addon Watchguard] Zigbee2MQTT"
description: ""
triggers:
  - minutes: "*"
    trigger: time_pattern
conditions:
  - condition: state
    entity_id: binary_sensor.zigbee2mqtt_bridge_connection_state
    state: unavailable
    for:
      hours: 0
      minutes: 5
      seconds: 0
actions:
  - repeat:
      until:
        - condition: state
          entity_id: binary_sensor.zigbee2mqtt_running
          state: "on"
          for:
            hours: 0
            minutes: 5
            seconds: 0
      sequence:
        - if:
            - condition: state
              entity_id: binary_sensor.zigbee2mqtt_running
              state: "off"
          then:
            - data:
                addon: 45df7312_zigbee2mqtt
              action: hassio.addon_start
            - delay:
                hours: 0
                minutes: 1
                seconds: 0
                milliseconds: 0
            - data: {}
              target:
                entity_id: binary_sensor.zigbee2mqtt_running
              action: homeassistant.update_entity
          else:
            - delay:
                hours: 0
                minutes: 0
                seconds: 30
                milliseconds: 0
            - data: {}
              target:
                entity_id: binary_sensor.zigbee2mqtt_running
              action: homeassistant.update_entity
mode: single
