---
alias: "[Addon Watchguard] Sungather"
description: ""
trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    minutes: "/15"

condition:
  - condition: sun
    after: sunrise
    before: sunset

  # Grace period after HA starts (requires sensor.ha_uptime_hours)
  - condition: template
    value_template: >
      {{ (as_timestamp(now()) - as_timestamp(states('sensor.ha_uptime_hours'))) > 300 }}

  - condition: or
    conditions:
      - condition: state
        entity_id: sensor.sungrow_sg5kd_daily_generation
        state: unavailable
        for:
          minutes: 5

      - condition: template
        value_template: >
          {% set e = 'sensor.sungrow_sg5kd_daily_generation' %}
          {% if has_value(e) %}
            {{ (as_timestamp(now()) - as_timestamp(states[e].last_updated)) / 60 > 240 }}
          {% else %}
            false
          {% endif %}

action:
  - action: hassio.addon_restart
    data:
      addon: 7b536ee6_sungather

  - action: notify.alert
    data:
      title: Sungather Restarted
      message: >
        Solar data hasn't been updated in 5 minutes, Sungather has been restarted
      data:
        tag: watchguard_sungather
        notification_id: watchguard_sungather
        push:
          badge: 1
          sound: none

mode: single
