pause:
  description: Pause one or all slots.
  fields:
    address:
      description: The IP address or hostname of the client. It can be found as part of the integration name.
      example: 'localhost'
    slot:
      description: The slot to pause. Be sure to include the 0 in front if needed. Leave this out to pause all slots.
      example: "01"

unpause:
  description: Unpause one or all slots.
  fields:
    address:
      description: The IP address or hostname of the client. It can be found as part of the integration name.
      example: 'localhost'
    slot:
      description: The slot to unpause. Be sure to include the 0 in front if needed. Leave this out to unpause all slots.
      example: "01"

shutdown:
  description: Shut down the client.
  fields:
    address:
      description: The IP address or hostname of the client. It can be found as part of the integration name.
      example: 'localhost'

request_work_server_assignment:
    description: Request a new assignment from the work server.
    fields:
      address:
        description: The IP address or hostname of the client. It can be found as part of the integration name.
        example: 'localhost'
  