---
alias: HACS - Refresh Sensor
id: hacs_sensor_refresh
initial_state: true
trigger:
  - platform: event
    event_type: hacs/repository
    event_data:
      action: install
action:
  - delay:
      seconds: 4
  - service: homeassistant.update_entity
    target:
      entity_id: sensor.hacs
