---
id: "influx2entity_yearlybomstats"
alias: "InfluxDB to Entity: Yearly BOM Stats"
description: "InfluxDB to Entity: Yearly BOM Stats"
trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    hours: "/1"
condition: []
action:
  - service: pyscript.influxdb2_query_to_entity
    data:
      query: >-
        import "timezone" option location = timezone.location(name:
        "Australia/Sydney") from(bucket: "homeassistant")
          |> range(start: -1y)
          |> filter(fn: (r) => r["_measurement"] == "°C")
          |> filter(fn: (r) => r["entity_id"] == "tamworth_airport_temp")
          |> filter(fn: (r) => r["_field"] == "value")
          |> drop(columns: ["friendly_name"])
          |> aggregateWindow(every: 1d9h, fn: max, createEmpty: true)
          |> fill(value: 0.0)
          |> yield(name: "max")
      entity_id: sensor.archive_bomtemp_max_365day
      unit_of_measurement: °C
      friendly_name: BOM - 365 Day - Max Temp
      icon: "mdi:thermometer"
  - service: pyscript.influxdb2_query_to_entity
    data:
      query: >-
        import "timezone" option location = timezone.location(name:
        "Australia/Sydney") from(bucket: "homeassistant")
          |> range(start: -1y)
          |> filter(fn: (r) => r["_measurement"] == "°C")
          |> filter(fn: (r) => r["entity_id"] == "tamworth_airport_temp")
          |> filter(fn: (r) => r["_field"] == "value")
          |> drop(columns: ["friendly_name"])
          |> aggregateWindow(every: 1d9h, fn: min, createEmpty: true)
          |> fill(value: 0.0)
          |> yield(name: "min")
      entity_id: sensor.archive_bomtemp_min_365day
      unit_of_measurement: °C
      friendly_name: BOM - 365 Day - Min Temp
      icon: "mdi:thermometer"
  - service: pyscript.influxdb2_query_to_entity
    data:
      query: >-
        import "timezone" option location = timezone.location(name:
        "Australia/Sydney") from(bucket: "homeassistant")
          |> range(start: -1y)
          |> filter(fn: (r) => r["_measurement"] == "°C")
          |> filter(fn: (r) => r["entity_id"] == "tamworth_airport_temp")
          |> filter(fn: (r) => r["_field"] == "value")
          |> drop(columns: ["friendly_name"])
          |> aggregateWindow(every: 1d, fn: spread, createEmpty: true)
          |> fill(value: 0.0)
          |> yield()
      entity_id: sensor.archive_bomtemp_range_365day
      unit_of_measurement: °C
      friendly_name: BOM - 365 Day - Temp Range
      icon: "mdi:thermometer"
  - service: pyscript.influxdb2_query_to_entity
    data:
      query: >-
        import "timezone" option location = timezone.location(name:
        "Australia/Sydney") from(bucket: "homeassistant")
          |> range(start: -1y)
          |> filter(fn: (r) => r["_measurement"] == "mm")
          |> filter(fn: (r) => r["entity_id"] == "tamworth_airport_rain_since_9am")
          |> filter(fn: (r) => r["_field"] == "value")
          |> drop(columns: ["friendly_name"])
          |> aggregateWindow(every: 1d9h, fn: max, createEmpty: true)
          |> fill(value: 0.0)
          |> yield(name: "max")
      entity_id: sensor.archive_bomrain_365day
      unit_of_measurement: mm
      friendly_name: BOM - Year - Rain
      icon: "mdi:water"
  - service: pyscript.influxdb2_query_to_entity
    data:
      query: >-
        import "timezone" option location = timezone.location(name:
        "Australia/Sydney") from(bucket: "homeassistant")
          |> range(start: -1y)
          |> filter(fn: (r) => r["_measurement"] == "mm")
          |> filter(fn: (r) => r["entity_id"] == "tamworth_airport_rain_since_9am")
          |> filter(fn: (r) => r["_field"] == "value")
          |> drop(columns: ["friendly_name"])
          |> aggregateWindow(every: 1d9h, fn: max, createEmpty: true)
          |> cumulativeSum()
          |> fill(value: 0.0)
          |> yield(name: "max")
      entity_id: sensor.archive_bomrain_365day_cume
      unit_of_measurement: mm
      friendly_name: BOM - Year - Rain Cume
      icon: "mdi:water"
mode: single
