---
sensor:
  - platform: rest
    timeout: 60
    scan_interval: 600
    force_update: true
    resource: https://stats.foldingathome.org/api/donor/bacco007
    name: Folding at Home Points
    value_template: '{{ value_json.credit }}'

  - platform: rest
    timeout: 60
    scan_interval: 600
    force_update: true
    resource: https://stats.foldingathome.org/api/donor/bacco007
    name: Folding at Home Work Units
    value_template: '{{ value_json.wus }}'

  - platform: rest
    timeout: 60
    scan_interval: 600
    force_update: true
    resource: https://stats.foldingathome.org/api/team/247478
    name: Folding at Home Team Points
    value_template: '{{ value_json.credit }}'

  - platform: rest
    timeout: 60
    scan_interval: 600
    force_update: true
    resource: https://stats.foldingathome.org/api/team/247478
    name: Folding at Home Team Work Units
    value_template: '{{ value_json.wus }}'
