---
homeassistant:
  customize:
    sensor.192_168_1_50_00_assigned:
      friendly_name: Assigned
    sensor.192_168_1_50_00_attempts:
      friendly_name: Attempts
    sensor.192_168_1_50_00_basecredit:
      friendly_name: Base Credit
    sensor.192_168_1_50_00_collection_server:
      friendly_name: Collection Server
    sensor.192_168_1_50_00_creditestimate:
      friendly_name: Credit Estimate
    sensor.192_168_1_50_00_deadline:
      friendly_name: Deadline
    sensor.192_168_1_50_00_error:
      friendly_name: Error
    sensor.192_168_1_50_00_estimated_time_finished:
      friendly_name: Estimate Time Finished
    sensor.192_168_1_50_00_frames_done:
      friendly_name: Frames Done
    sensor.192_168_1_50_00_idle:
      friendly_name: Idle
    sensor.192_168_1_50_00_next_attempt:
      friendly_name: Next Attempt
    sensor.192_168_1_50_00_percentdone:
      friendly_name: Percent Done
    sensor.192_168_1_50_00_points_per_day:
      friendly_name: Points per Day
    sensor.192_168_1_50_00_project:
      friendly_name: Project
    sensor.192_168_1_50_00_reason:
      friendly_name: Reason
    sensor.192_168_1_50_00_status:
      friendly_name: Status
    sensor.192_168_1_50_00_time_per_frame:
      friendly_name: Time per Frame
    sensor.192_168_1_50_00_timeout:
      friendly_name: Timeout
    sensor.192_168_1_50_00_total_frames:
      friendly_name: Total Frames
    sensor.192_168_1_50_00_waiting_on:
      friendly_name: Waiting On
    sensor.192_168_1_50_00_work_server:
      friendly_name: Work Server
sensor:
  - platform: rest
    timeout: 60
    scan_interval: 600
    force_update: true
    resource: https://stats.foldingathome.org/api/donor/bacco007
    name: Folding at Home Points
    value_template: "{{ value_json.credit }}"

  - platform: rest
    timeout: 60
    scan_interval: 600
    force_update: true
    resource: https://stats.foldingathome.org/api/donor/bacco007
    name: Folding at Home Work Units
    value_template: "{{ value_json.wus }}"

  - platform: rest
    timeout: 60
    scan_interval: 600
    force_update: true
    resource: https://stats.foldingathome.org/api/team/247478
    name: Folding at Home Team Points
    value_template: "{{ value_json.credit }}"

  - platform: rest
    timeout: 60
    scan_interval: 600
    force_update: true
    resource: https://stats.foldingathome.org/api/team/247478
    name: Folding at Home Team Work Units
    value_template: "{{ value_json.wus }}"
