---
homeassistant:
  customize:
    binary_sensor.iss:
      icon: mdi:satellite-variant
      friendly_name: ISS Visible

binary_sensor:
  - platform: iss

sensor:
  - platform: template
    sensors:
      iss_peopleinspace:
        friendly_name: 'People in Space'
        value_template: '{{ states.binary_sensor.iss.attributes["number_of_people_in_space"] }}'
        entity_id: binary_sensor.iss
