---
sensor:
  - platform: opennem
    region: nsw1
    monitored_conditions:
      - battery_charging
      - battery_discharging
      - biomass
      - black_coal
      - brown_coal
      - exports
      - demand
      - distillate
      - fossilfuel
      - renewables
      - gas_ccgt
      - gas_ocgt
      - gas_recip
      - gas_steam
      - generation
      - hydro
      - imports
      - price
      - pumps
      - rooftop_solar
      - solar
      - temperature
      - wind

  - platform: opennem
    region: vic1
    name: test
    monitored_conditions:
      - brown_coal
