---
trigger:
  - platform: event
    event_type: bubble_card_update_modules
sensor:
  - name: "Bubble Card Modules"
    state: "saved"
    attributes:
      modules: "{{ trigger.event.data.modules }}"
      last_updated: "{{ trigger.event.data.last_updated }}"
