---
trigger:
  - platform: homeassistant
    event: start

  - platform: event
    event_type: event_template_reloaded

  - platform: state
    entity_id: sensor.time
binary_sensor:
  - name: "[Connected] MQTT"
    unique_id: connected_mqtt
    icon: mdi:sort-clock-descending
    picture: https://brands.home-assistant.io/mqtt/icon.png
    device_class: connectivity
    state: "{{ integration_entities('mqtt')|select('has_value')|list|count > 0 }}"
    attributes:
      category: homeassistant
  - name: "[Connected] Uptime Kuma"
    unique_id: connected_uptime_kuma
    icon: mdi:sort-clock-descending
    picture: https://brands.home-assistant.io/uptime_kuma/icon.png
    device_class: connectivity
    state: "{{ integration_entities('uptime_kuma')|select('has_value')|list|count > 0 }}"
    attributes:
      category: homeassistant
  - name: "[Connected] OpenUV"
    unique_id: connected_openuv
    icon: mdi:weather-sunny-alert
    picture: https://brands.home-assistant.io/openuv/icon.png
    device_class: connectivity
    state: "{{ integration_entities('openuv')|select('has_value')|list|count > 0 }}"
    attributes:
      category: homeassistant
  - name: "[Connected] GDACS"
    unique_id: connected_gdacs
    icon: mdi:home-flood
    picture: https://brands.home-assistant.io/gdacs/icon.png
    device_class: connectivity
    state: "{{ integration_entities('gdacs')|select('has_value')|list|count > 0 }}"
    attributes:
      category: homeassistant
  - name: "[Connected] NSW RFS"
    unique_id: connected_nswrfs
    icon: mdi:fire-alert
    picture: https://brands.home-assistant.io/nsw_rural_fire_service_fire_danger/icon.png
    device_class: connectivity
    state: "{{ integration_entities('nsw_rural_fire_service_feed')|select('has_value')|list|count > 0 }}"
    attributes:
      category: homeassistant
  - name: "[Connected] WAQI"
    unique_id: connected_waqi
    icon: mdi:smog
    picture: https://brands.home-assistant.io/waqi/icon.png
    device_class: connectivity
    state: "{{ integration_entities('waqi')|select('has_value')|list|count > 0 }}"
    attributes:
      category: homeassistant
  - name: "[Connected] Weatherflow Local"
    unique_id: weatherflow_local_connected
    icon: mdi:weather-lightning-rainy
    picture: https://brands.home-assistant.io/weatherflow/icon.png
    device_class: connectivity
    state: "{{ has_value('sensor.tempest_st_00056115_status') }}"
    attributes:
      category: homeassistant
  - name: "[Connected] Weatherflow Cloud"
    unique_id: weatherflow_cloud_connected
    icon: mdi:weather-lightning-rainy
    picture: https://brands.home-assistant.io/weatherflow/icon.png
    device_class: connectivity
    state: "{{ integration_entities('weatherflow_forecast')|select('has_value')|list|count > 0 }}"
    attributes:
      category: homeassistant
  - name: "[Connected] Sungather"
    unique_id: connected_sungather
    icon: mdi:solar-power-variant-outline
    device_class: connectivity
    state: "{{ 'True' if is_state('binary_sensor.sungather_running', 'on') else 'False' }}"
    attributes:
      category: homeassistant
  - name: "[Connected] PirateWeather"
    unique_id: connected_pirateweather
    icon: mdi:weather-sunny-alert
    picture: https://brands.home-assistant.io/pirateweather/icon.png
    device_class: connectivity
    state: "{{ integration_entities('pirateweather')|select('has_value')|list|count > 0 }}"
    attributes:
      category: homeassistant
  - name: "[Connected] Eufy Security"
    unique_id: connected_eufysecurity
    icon: mdi:cctv-off
    device_class: connectivity
    state: "{{ integration_entities('eufy_security')|select('has_value')|list|count > 0 }}"
    attributes:
      category: homeassistant
  - name: "[Connected] Bureau of Meteorology"
    unique_id: connected_bureauofmeteorology
    icon: mdi:weather-lightning-rainy
    device_class: connectivity
    state: "{{ integration_entities('bureau_of_meteorology')|select('has_value')|list|count > 0 }}"
    attributes:
      category: homeassistant
  - name: "[Connected] AdGuard"
    unique_id: connected_adguard
    icon: mdi:shield-account
    device_class: connectivity
    state: "{{ integration_entities('adguard')|select('has_value')|list|count > 0 }}"
    attributes:
      category: homeassistant
  - name: "[Connected] Solcast Solar"
    unique_id: connected_solcast_solar
    icon: mdi:solar-power-variant
    device_class: connectivity
    state: "{{ integration_entities('solcast_solar')|select('has_value')|list|count > 0 }}"
    attributes:
      category: homeassistant
  - name: "[Connected] Forecast Solar"
    unique_id: connected_forecast_solar
    icon: mdi:solar-power-variant
    device_class: connectivity
    state: "{{ integration_entities('forecast_solar')|select('has_value')|list|count > 0 }}"
    attributes:
      category: homeassistant
  - name: "[Connected] LG SmartThinq"
    unique_id: connected_lg_smartthinq
    icon: si:lg
    device_class: connectivity
    state: "{{ integration_entities('smartthinq_sensors')|select('has_value')|list|count > 0 }}"
    attributes:
      category: homeassistant
  - name: "[Connected] Synology"
    unique_id: connected_synology_dsm
    icon: mdi:nas
    device_class: connectivity
    state: "{{ integration_entities('synology_dsm')|select('has_value')|list|count > 0 }}"
    attributes:
      category: homeassistant
  - name: "[Connected] Spotify"
    unique_id: connected_spotify
    icon: mdi:spotify
    device_class: connectivity
    state: "{{ integration_entities('spotify')|select('has_value')|list|count > 0 }}"
    attributes:
      category: homeassistant
  - name: "[Connected] Apple TV"
    unique_id: connected_apple_tv
    icon: mdi:apple
    device_class: connectivity
    state: "{{ integration_entities('apple_tv')|select('has_value')|list|count > 0 }}"
    attributes:
      category: homeassistant
  - name: "[Connected] HDHomeRun"
    unique_id: connected_hdhomerun
    icon: mdi:television-box
    device_class: connectivity
    state: "{{ integration_entities('hdhomerun')|select('has_value')|list|count > 0 }}"
    attributes:
      category: homeassistant
  - name: "[Connected] Unifi"
    unique_id: connected_unifi
    icon: mdi:wifi
    device_class: connectivity
    state: "{{ integration_entities('unifi')|select('has_value')|list|count > 0 }}"
    attributes:
      category: homeassistant
  - name: "[Connected] Speedtest"
    unique_id: connected_speedtest
    icon: mdi:speedtest
    device_class: connectivity
    state: "{{ integration_entities('speedtestdotnet')|select('has_value')|list|count > 0 }}"
    attributes:
      category: homeassistant
  - name: "[Connected] iCal"
    unique_id: connected_ical
    icon: mdi:calendar
    device_class: connectivity
    state: "{{ integration_entities('ical')|select('has_value')|list|count > 0 }}"
    attributes:
      category: homeassistant
  - name: "[Connected] iCloud 3"
    unique_id: connected_icloud3
    icon: mdi:apple-icloud
    device_class: connectivity
    state: "{{ integration_entities('icloud3')|select('has_value')|list|count > 0 }}"
    attributes:
      category: homeassistant
  - name: "[Connected] Bluetooth"
    unique_id: connected_bluetooth
    icon: mdi:bluetooth
    device_class: connectivity
    state: >
      {{ (expand(state_attr('sensor.devices_bluetooth', 'entity_id'))
            | selectattr('state', 'eq', 'home') | list | count > 0
          or expand(state_attr('sensor.devices_bluetooth_le', 'entity_id'))
            | selectattr('state', 'eq', 'home') | list | count > 0)
          and is_state('input_boolean.alerts_bluetooth','on') }}
    attributes:
      category: homeassistant

sensor:
  - name: "[Connected] Offline Integrations"
    unique_id: connected_offline_integrations
    icon: "{{ iif(states(this.entity_id) == '0','mdi:api','mdi:api-off') }}"
    state: >
      {% set entities = state_attr(this.entity_id,'entity_id') %}
      {{ entities|count if entities != none else entities }}
    attributes:
      category: homeassistant
      entity_id: >
        {{ expand('group.connectivity_monitors')
            |selectattr('state','eq','off')|map(attribute='entity_id')|list|sort }}
