---
sensor:
  - name: statistics_chart_grouping
    unique_id: statistics_chart_grouping
    state: |
      {%- set grouping={
        'day':'h',
        'week':'d',
        'month':'d',
        'year':'d'}
      %}
      {%- set range = states('input_select.statistics_chart_range') %}
      {{ grouping[range] }}
  - name: statistics_chart_span
    unique_id: statistics_chart_span
    state: |
      {%- macro last_date_in_range(date_str,range) -%}
        {%- set date=as_timestamp(date_str)|timestamp_local()|as_datetime() -%}
        {%- if range=='day' -%}
          {%- set end_date=date -%}
        {%- elif range=='week' -%}
          {%- set end_date=date + timedelta(days=(6-date.weekday())) -%}
        {%- elif range=='month' -%}
          {%- set month=(date.month % 12) + 1 -%}
          {%- set year=date.year+iif(date.month==12,1,0) -%}
          {%- set end_date=strptime(year|string + '-' + month|string + '-01', '%Y-%m-%d')-timedelta(days=1) -%}
        {%- elif range=='year' -%}
          {%- set end_date=strptime(date.year|string + '-12-31', '%Y-%m-%d') -%}
        {%- endif -%}
        {{ as_timestamp(end_date)|timestamp_local() -}}
      {%- endmacro -%}
      {%- set range = states('input_select.statistics_chart_range') %}
      {%- set date_str = states('input_datetime.statistics_chart_date') %}
      {%- set spans={
        'day':'24',
        'week':'7',
        'month':(last_date_in_range (strptime(date_str, '%Y-%m-%d'),range)|as_datetime()).day,
        'year':last_date_in_range (strptime(date_str, '%Y-%m-%d'),range)|as_timestamp(0)|timestamp_custom('%j',0)|int +1}
      %}
      {{ spans[range] }}
  - name: statistics_chart_period
    unique_id: statistics_chart_period
    state: |
      {%- set periods={
        'day':'hour',
        'week':'day',
        'month':'day',
        'year':'day'}
      %}
      {%- set range = states('input_select.statistics_chart_range') %}
      {{ periods[range] }}
  - name: statistics_chart_offset
    unique_id: statistics_chart_offset
    state: |
      {%- macro last_date_in_range(date_str,range) -%}
        {%- set date=as_timestamp(date_str)|timestamp_local()|as_datetime() -%}
        {%- if range=='day' -%}
          {% set end_date = date + timedelta(days=1) -%}
        {%- elif range=='week' -%}
          {%- set end_date=date + timedelta(days=(6-date.weekday())) -%}
        {%- elif range=='month' -%}
          {%- set month=(date.month % 12) + 1 -%}
          {%- set year=date.year+iif(date.month==12,1,0) -%}
          {%- set end_date=strptime(year|string + '-' + month|string + '-01', '%Y-%m-%d')-timedelta(days=1) -%}
        {%- elif range=='year' -%}
          {%- set end_date=strptime(date.year|string + '-12-31', '%Y-%m-%d') -%}
        {%- endif -%}
        {{ as_timestamp(end_date) -}}
      {%- endmacro -%}
      {%- set range = states('input_select.statistics_chart_range') %}
      {%- set date_str = states('input_datetime.statistics_chart_date') %}
      {%- set offset = last_date_in_range(strptime(date_str, '%Y-%m-%d'),range)|int - now()|as_timestamp(0) -%}
      {%- if states('sensor.statistics_chart_grouping') == 'h' %}
        {%- set offset=(offset/60/60)|round(method='ceil') %}
      {%- else %}
        {%- set offset=(offset/60/60/24)|round(method='ceil') + 1 %}
      {%- endif %}
      {{ iif(offset >= 0,'+','') }}{{ offset }}{{ states('sensor.statistics_chart_grouping') }}
