---
# https://github.com/jazzyisj/home-assistant-config/blob/master/packages/package_unavailable_entities_sensor_gist.yaml

sensor:
  - name: "Unavailable Entities"
    unique_id: unavailable_entities
    icon: "{{ iif(states(this.entity_id)|int(-1) > 0,'mdi:alert-circle','mdi:check-circle') }}"
    state_class: measurement
    unit_of_measurement: entities
    state: >
      {% set entities = state_attr(this.entity_id,'entity_id') %}
      {{ entities|count if entities != none else none }}
    attributes:
      entity_id: >
        {%- if state_attr('group.ignored_unavailable_entities','entity_id') != none %}
          {%- set ignore_seconds = 60 %}
          {%- set ignore_ts = (now().timestamp() - ignore_seconds)|as_datetime %}
          {%- set entities = states|rejectattr('domain','in',['group','button','media_player','device_tracker','camera', 'update', 'remote', 'switch', 'light'])|selectattr('state','in',['unavailable','unknown','none'])|list %}
          {%- set buttons = states.button|selectattr('state','eq','unavailable')|list %}
          {{ (entities + buttons)
            |rejectattr('entity_id','in',state_attr('group.ignored_unavailable_entities','entity_id'))
            |rejectattr('entity_id','search','rssfeed_')
            |rejectattr('entity_id','search','button.')
            |rejectattr('entity_id','search','select.')
            |rejectattr('entity_id','search','_color')
            |rejectattr('entity_id','search','wunder')
            |rejectattr('entity_id','search','gosungrow')
            |rejectattr('entity_id','search','z2m_plug')
            |rejectattr('entity_id','in',expand(integration_entities('browser_mod'))|map(attribute='entity_id')|list)
            |rejectattr('entity_id','in',expand(integration_entities('gdacs'))|map(attribute='entity_id')|list)
            |rejectattr('entity_id','in',expand(integration_entities('github'))|map(attribute='entity_id')|list)
            |rejectattr('entity_id','in',expand(integration_entities('glances'))|map(attribute='entity_id')|list)
            |rejectattr('entity_id','in',expand(integration_entities('hassio'))|map(attribute='entity_id')|list)
            |rejectattr('entity_id','in',expand(integration_entities('openuv'))|map(attribute='entity_id')|list)
            |rejectattr('entity_id','in',expand(integration_entities('utility_meter'))|map(attribute='entity_id')|list)
            |rejectattr('entity_id','in',expand(integration_entities('waqi'))|map(attribute='entity_id')|list)
            |rejectattr('entity_id','in',expand(integration_entities('tautulli'))|map(attribute='entity_id')|list)
            |rejectattr('entity_id','in',expand(integration_entities('here_travel_time'))|map(attribute='entity_id')|list)
            |rejectattr('entity_id','in',expand(integration_entities('tomorrowio'))|map(attribute='entity_id')|list)
            |rejectattr('entity_id','in',expand(integration_entities('pirateweather'))|map(attribute='entity_id')|list)
            |rejectattr('entity_id','in',expand(integration_entities('proxmoxve'))|map(attribute='entity_id')|list)
            |rejectattr('entity_id','in',expand(integration_entities('blitzortung'))|map(attribute='entity_id')|list)
            |rejectattr('entity_id','in',expand(integration_entities('ble_monitor'))|map(attribute='entity_id')|list)
            |rejectattr('entity_id','in',expand(integration_entities('waternsw'))|map(attribute='entity_id')|list)
            |rejectattr('entity_id','in',expand(integration_entities('ical'))|map(attribute='entity_id')|list)
            |rejectattr('entity_id','in',expand(integration_entities('bureau_of_meteorology'))|map(attribute='entity_id')|list)
            |rejectattr('entity_id','in',expand(integration_entities('weatherflow'))|map(attribute='entity_id')|list)
            |rejectattr('entity_id','in',expand(integration_entities('eufy_security'))|map(attribute='entity_id')|list)
            |rejectattr('entity_id','in',expand(integration_entities('browser_mod'))|map(attribute='entity_id')|list)
            |rejectattr('last_changed','ge',ignore_ts)
            |map(attribute='entity_id')|list }}
        {%- endif %}

  - name: "Unknown/Unavailable/None Entities"
    unique_id: unk_una_none_entities
    icon: "{{ 'mdi:alert-circle' if states(this.entity_id)|int(0) > 0 else 'mdi:check-circle' }}"
    unit_of_measurement: entities
    state: >
      {{ states|selectattr('state','in',['unavailable','unknown','none'])|list|length }}
    attributes:
      unknown: >
        {%- if state_attr('group.ignored_unavailable_entities','entity_id') != none %}
          {%- set ignore_seconds = 60 %}
          {%- set ignore_ts = (now().timestamp() - ignore_seconds)|as_datetime %}
          {%- set unknown = states|selectattr('state','eq','unknown')|rejectattr('domain','in',['group','button','media_player','device_tracker','camera', 'update', 'remote'])|map(attribute='entity_id')|list %}
          {{ unknown|list }}
        {%- endif %}
      unknown_count: >
        {{ state_attr(this.entity_id, 'unknown') | list | count }}
      unavailable: >
        {%- if state_attr('group.ignored_unavailable_entities','entity_id') != none %}
          {%- set ignore_seconds = 60 %}
          {%- set ignore_ts = (now().timestamp() - ignore_seconds)|as_datetime %}
          {%- set unknown = states|selectattr('state','eq','unavailable')|rejectattr('domain','in',['group','button','media_player','device_tracker','camera', 'update', 'remote'])|map(attribute='entity_id')|list %}
          {{ unknown|list }}
        {%- endif %}
      unavailable_count: >
        {{ state_attr(this.entity_id, 'unavailable') | list | count }}
      none: >
        {%- if state_attr('group.ignored_unavailable_entities','entity_id') != none %}
          {%- set ignore_seconds = 60 %}
          {%- set ignore_ts = (now().timestamp() - ignore_seconds)|as_datetime %}
          {%- set unknown = states|selectattr('state','eq','none')|rejectattr('domain','in',['group','button','media_player','device_tracker','camera', 'update', 'remote'])|map(attribute='entity_id')|list %}
          {{ unknown|list }}
        {%- endif %}
      none_count: >
        {{ state_attr(this.entity_id, 'none') | list | count }}
