---
binary_sensor:
  - name: Plex Update Available
    unique_id: plex_updateavailable
    device_class: problem
    state: >-
      {% if states('sensor.plex_latest_version') | lower in ['unknown', 'unavailable', 'none'] %}
        false
      {% else %}
        {{ states('sensor.plex_latest_version') != states('sensor.plex_installed_version') }}
      {% endif %}

  - name: Radarr Update Available
    unique_id: radarr_updateavailable
    device_class: problem
    state: >-
      {% if states('sensor.radarr_latest_update') | lower in ['unknown', 'unavailable', 'none'] %}
        false
      {% elif state_attr('sensor.radarr_latest_update', 'installed') == true %}
        false
      {% else %}
        {{ states('sensor.radarr_latest_update') != states('sensor.radarr_installed_version') }}
      {% endif %}

  - name: Sonarr Update Available
    unique_id: sonarr_updateavailable
    device_class: problem
    state: >-
      {% if states('sensor.sonarr_latest_update') | lower in ['unknown', 'unavailable', 'none'] %}
        false
      {% elif state_attr('sensor.sonarr_latest_update', 'installed') == true %}
        false
      {% else %}
        {{ states('sensor.sonarr_latest_update') != states('sensor.sonarr_installed_version') }}
      {% endif %}
