snapshot_full:
  description: Take a snapshot of all home assistant addons and folders.
  fields:
    name: 
      description: Backup name.
      example: "Automatic Backup {{ now().strftime('%Y-%m-%d') }}"
    password:
      description: Optional password to secure backup.
      example: "1234"
    keep_days:
      description: The number of days to keep the backup.
      example: "2"
    exclude:
      description: Addons/Folders to exclude from the backup.
      example: '{"addons": ["MariaDB"], "folders": ["Local add-ons", "share"]}'
    backup_path:
      description: Alternative directory to copy backup to after creation.
      example: /usb_drive

snapshot_partial:
  description: Take a snapshot of the specified home assistant addons and folders.
  fields:
    name: 
      description: Backup Name.
      example: "Automatic Backup {{ now().strftime('%Y-%m-%d') }}"
    addons: 
      description: List of addons to backup (name or slug).
      example:
        - grafana
        - Configurator
        - core_mariadb
    folders: 
      description: List of folders to backup.
      example:
        - homeassistant
        - Share
        - Local add-ons
        - ssl
    password:
      description: Optional password to secure backup.
      example: "1234"
    keep_days:
      description: The number of days to keep the backup.
      example: "2"
    backup_path:
      description: Alternative directory to copy backup to after creation.
      example: /usb_drive

purge:
  description: Purge expired backups.