---
sensor:
  - platform: here_travel_time
    entity_namespace: here_travel
    name: Home to Work (Car)
    api_key: !secret here_apikey
    origin_entity_id: zone.home
    destination_entity_id: zone.trc
    mode: car

  - platform: here_travel_time
    entity_namespace: here_travel
    name: Home to Work (Walk)
    api_key: !secret here_apikey
    origin_entity_id: zone.home
    destination_entity_id: zone.trc
    mode: pedestrian

  - platform: here_travel_time
    entity_namespace: here_travel
    name: Tom to Home
    api_key: !secret here_apikey
    origin_entity_id: device_tracker.tbiphone11_3
    destination_entity_id: zone.home
    mode: car

  - platform: here_travel_time
    entity_namespace: here_travel
    name: Tom to Work
    api_key: !secret here_apikey
    origin_entity_id: device_tracker.tbiphone11_3
    destination_entity_id: zone.trc
    mode: car

  - platform: template
    sensors:
      here_travel_tom_to_work_arrivetime:
        friendly_name: Tom arrival time (Work)
        entity_id: sensor.time
        value_template: >
          {% set minutes = states('sensor.here_travel_tom_to_work') | int %}
          {{ (as_timestamp(now()) + (minutes * 60)) | timestamp_custom('%H:%M') }}
      here_travel_tom_to_home_arrivetime:
        friendly_name: Tom arrival time (Home)
        entity_id: sensor.time
        value_template: >
          {% set minutes = states('sensor.here_travel_tom_to_home') | int %}
          {{ (as_timestamp(now()) + (minutes * 60)) | timestamp_custom('%H:%M') }}
