---
sensor:
  - platform: here_travel_time
    entity_namespace: here_travel
    name: Home to Work (Car)
    api_key: !secret here_apikey
    origin_entity_id: zone.home
    destination_entity_id: zone.trc
    mode: car
  - platform: here_travel_time
    entity_namespace: here_travel
    name: Home to Work (Walk)
    api_key: !secret here_apikey
    origin_entity_id: zone.home
    destination_entity_id: zone.trc
    mode: pedestrian
  - platform: here_travel_time
    entity_namespace: here_travel
    name: Tom to Home
    api_key: !secret here_apikey
    origin_entity_id: device_tracker.tbiphone11
    destination_entity_id: zone.home
    mode: car
  - platform: here_travel_time
    entity_namespace: here_travel
    name: Tom to Work
    api_key: !secret here_apikey
    origin_entity_id: device_tracker.tbiphone11
    destination_entity_id: zone.trc
    mode: car
