---
sensor:
  - platform: waze_travel_time
    entity_namespace: waze_travel
    origin: zone.home
    destination: zone.trc
    region: 'AU'
    name: Home to Work
    realtime: true
    units: metric
    vehicle_type: car
  - platform: waze_travel_time
    entity_namespace: waze_travel
    origin: device_tracker.tbiphone11_3
    destination: zone.trc
    region: 'AU'
    name: Tom to Work
    realtime: true
    units: metric
    vehicle_type: car
  - platform: waze_travel_time
    entity_namespace: waze_travel
    origin: device_tracker.tbiphone11_3
    destination: zone.home
    region: 'AU'
    name: Tom to Home
    realtime: true
    units: metric
    vehicle_type: car
  - platform: template
    sensors:
      waze_travel_tom_to_work_arrivetime:
        friendly_name: Tom arrival time (Work)
        entity_id: sensor.time
        value_template: >
          {% set minutes = states('sensor.waze_travel_tom_to_work') | int %}
          {{ (as_timestamp(now()) + (minutes * 60)) | timestamp_custom('%H:%M') }}
      waze_travel_tom_to_home_arrivetime:
        friendly_name: Tom arrival time (Home)
        entity_id: sensor.time
        value_template: >
          {% set minutes = states('sensor.waze_travel_tom_to_home') | int %}
          {{ (as_timestamp(now()) + (minutes * 60)) | timestamp_custom('%H:%M') }}
