---
homeassistant:
  customize:
    binary_sensor.tbsh01_ha_dockermon_db:
      friendly_name: MariaDB (TBSH01)
    binary_sensor.tbsh01_ha_dockermon_duplicati:
      friendly_name: Duplicati (TBSH01)
    binary_sensor.tbsh01_ha_dockermon_glances:
      friendly_name: Glances (TBSH01)
    binary_sensor.tbsh01_ha_dockermon_guacamole:
      friendly_name: Guacamole (TBSH01)
    binary_sensor.tbsh01_ha_dockermon_ha_dockermon:
      friendly_name: HA Dockermon (TBSH01)
    binary_sensor.tbsh01_ha_dockermon_netdata:
      friendly_name: Netdata (TBSH01)
    binary_sensor.tbsh01_ha_dockermon_nginxproxymanager:
      friendly_name: NGINX Proxy Manager (TBSH01)
    binary_sensor.tbsh01_ha_dockermon_ouroboros:
      friendly_name: Ouroboros (TBSH01)
    binary_sensor.tbsh01_ha_dockermon_portainer:
      friendly_name: Portainer (TBSH01)
    binary_sensor.tbsh01_ha_dockermon_unifi:
      friendly_name: Unifi Controller (TBSH01)
    binary_sensor.vmtbsh01_ha_dockermon_duplicati:
      friendly_name: Duplicati (vmTBSH01)
    binary_sensor.vmtbsh01_ha_dockermon_glances:
      friendly_name: Glances (vmTBSH01)
    binary_sensor.vmtbsh01_ha_dockermon_grafana:
      friendly_name: Grafana (vmTBSH01)
    binary_sensor.vmtbsh01_ha_dockermon_ha_dockermon:
      friendly_name: HA Dockermon (vmTBSH01)
    binary_sensor.vmtbsh01_ha_dockermon_jackett:
      friendly_name: Jackett (vmTBSH01)
    binary_sensor.vmtbsh01_ha_dockermon_netdata:
      friendly_name: Netdata (vmTBSH01)
    binary_sensor.vmtbsh01_ha_dockermon_nzbhydra2:
      friendly_name: NZBHydra2 (vmTBSH01)
    binary_sensor.vmtbsh01_ha_dockermon_ouroboros:
      friendly_name: Ouroboros (vmTBSH01)
    binary_sensor.vmtbsh01_ha_dockermon_portainer:
      friendly_name: Portainer (vmTBSH01)
    binary_sensor.vmtbsh01_ha_dockermon_radarr:
      friendly_name: Radarr (vmTBSH01)
    binary_sensor.vmtbsh01_ha_dockermon_sabnzbd:
      friendly_name: SABnzbd (vmTBSH01)
    binary_sensor.vmtbsh01_ha_dockermon_sonarr:
      friendly_name: Sonarr (vmTBSH01)
    binary_sensor.vmtbsh01_ha_dockermon_tautulli:
      friendly_name: Tautulli (vmTBSH01)
    binary_sensor.vmtbsh01_ha_dockermon_transmission:
      friendly_name: Transmission (vmTBSH01)
    binary_sensor.vmtbsh01_ha_dockermon_tvheadend:
      friendly_name: TVHeadend (vmTBSH01)
    binary_sensor.vmtbsh02_ha_dockermon_chronograf:
      friendly_name: Chronograf (vmTBSH02)
    binary_sensor.vmtbsh02_ha_dockermon_duplicati:
      friendly_name: Duplicati (vmTBSH02)
    binary_sensor.vmtbsh02_ha_dockermon_glances:
      friendly_name: Glances (vmTBSH02)
    binary_sensor.vmtbsh02_ha_dockermon_ha_dockermon:
      friendly_name: HA Dockermon (vmTBSH02)
    binary_sensor.vmtbsh02_ha_dockermon_hassio_dns:
      friendly_name: Hass.io DNS (vmTBSH02)
    binary_sensor.vmtbsh02_ha_dockermon_hassio_supervisor:
      friendly_name: Hass.io Supervisor (vmTBSH02)
    binary_sensor.vmtbsh02_ha_dockermon_homeassistant:
      friendly_name: Home Assistant (vmTBSH02)
    binary_sensor.vmtbsh02_ha_dockermon_influxdb:
      friendly_name: InfluxDB (vmTBSH02)
    binary_sensor.vmtbsh02_ha_dockermon_kapacitor:
      friendly_name: Kapacitor (vmTBSH02)
    binary_sensor.vmtbsh02_ha_dockermon_netdata:
      friendly_name: Netdata (vmTBSH02)
    binary_sensor.vmtbsh02_ha_dockermon_ouroboros:
      friendly_name: Ouroboros (vmTBSH02)
    binary_sensor.vmtbsh02_ha_dockermon_portainer:
      friendly_name: Portainer (vmTBSH02)
    binary_sensor.vmtbsh02_ha_dockermon_telegraf:
      friendly_name: Telegraf (vmTBSH02)

binary_sensor:
  - platform: hadockermon
    entity_namespace: vmTBSH01
    host: !secret vmTBSH01_ipaddress
    port: !secret hadm_port
    stats: true

  - platform: hadockermon
    entity_namespace: vmTBSH02
    host: !secret vmTBSH02_ipaddress
    port: !secret hadm_port
    stats: true

  - platform: hadockermon
    entity_namespace: TBSH01
    host: !secret TBSH01_ipaddress
    port: !secret hadm_port
    stats: true
