---
sensor:
  - platform: netdata
    host: 192.168.1.60
    port: 19999
    entity_namespace: netdata
    name: pveTBSH
    resources:
      system_cpu_idle:
        data_group: system.cpu
        element: idle
        icon: mdi:chip
      system_load_1:
        data_group: system.load
        element: load1
      system_load_5:
        data_group: system.load
        element: load5
      system_load_15:
        data_group: system.load
        element: load15
