---
pi_hole:
  host: !secret pihole_host

sensor:
  ###
  ## Pi-Hole
  ###
  - platform: pi_hole

  - platform: rest
    name: Pi-Hole Version
    json_attributes:
      - core_update
      - web_update
      - FTL_update
      - core_current
      - web_current
      - FTL_current
      - core_latest
      - web_latest
      - FTL_latest
    value_template: '{{ value_json["core_update"] }}'
    resource: "http://192.168.1.40/admin/api.php?versions"

  - platform: rest
    name: Pi-Hole Status
    json_attributes:
      - value_json
    resource: "http://192.168.1.40/admin/api.php?status"
    value_template: '{{ value_json["status"] }}'

binary_sensor:
  - platform: template
    sensors:
      servicestatus_pihole:
        friendly_name: Pi-Hole (PiServ)
        entity_id: sensor.pi_hole_status
        value_template: "{{ is_state('sensor.pi_hole_status', 'enabled') }}"
        icon_template: >-
          {% if is_state('sensor.pi_hole_status', 'enabled') %}
            mdi:pi-hole
          {% else %}
            mdi:pi-hole
          {% endif %}

switch:
  - platform: command_line
    scan_interval: 5
    switches:
      pihole_switch:
        friendly_name: "Ad Blocking"
        command_on: "curl -X GET 'http://192.168.1.40/admin/api.php?enable&auth='"
        command_off: "curl -X GET 'http://192.168.1.40/admin/api.php?disable=600&auth='"
        command_state: "curl -X GET 'http://192.168.1.40/admin/api.php?status&auth='"
        value_template: "{{ value_json.status == 'enabled' }}"
