---
alias: "System - Database Repack (Weekly)"
id: database_repack
mode: single
trigger:
  - platform: time
    at: "02:00"
condition:
  - condition: time
    weekday:
      - sun
      - tue
      - thu
action:
  - service: recorder.purge
    data:
      apply_filter: true
      repack: true
