"""Constants for the Amber Electric integration."""

DOMAIN = "amber_electric"

ATTR_NEM_TIME = "nem_time"
ATTR_PERCENTILE_RANK = "percentile_rank"
ATTR_PERIOD_DELTA = "period_delta"
ATTR_PERIOD_START = "period_start"
ATTR_PERIOD_END = "period_end"
ATTR_PERIOD_TYPE = "period_type"
ATTR_WHOLESALE_KWH_PRICE = "wholesale_kwh_price"
ATTR_RENEWABLES_PERCENTAGE = "renewables_percentage"

CURRENCY_AUD = "AUD"
LOSS_FACTOR = "loss_factor"
AMBER_DAILY_PRICE = "amber_daily_price"
GREEN_KWH_PRICE = "green_kwh_price"
LOSS_FACTOR = "loss_factor"
MARKET_KWH_PRICE = "market_kwh_price"
NETWORK_DAILY_PRICE = "network_daily_price"
NETWORK_KWH_PRICE = "network_kwh_price"
NETWORK_PROVIDER = "network_provider"
OFFSET_KWH_PRICE = "offset_kwh_price"
TOTAL_DAILY_PRICE = "total_daily_price"
TOTAL_FIXED_KWH_PRICE = "total_fixed_kwh_price"

MANUFACTURER = "Amber Electric"