---
alias: Generational Backup - 3 Hourly
trigger:
  platform: time_pattern
  hours: "/3"
action:
  - service: auto_backup.snapshot_partial # Only perform a partial snapshot to save storage.
    data_template:
      name: "AutoBackup: {{ now().strftime('%a, %-I:%M %p (%d/%m/%Y)') }}"
      addons:
        - core_mariadb
      folders:
        - homeassistant
        - share
        - ssl
        - addons/local
      keep_days: 2
