---
alias: Admin - Home Assistant Stopped
trigger:
  - platform: homeassistant
    event: shutdown
action:
  - service: notify.slack
    data_template:
      message: ""
      target: "#tbsmarthome"
      data:
        attachments:
          - color: >
              #800400
            title: >
              Home Assistant Stopped
            text: |
              Home Assistant Stopped
