---
alias: Admin - Potential Breaking Changes
initial_state: true
trigger:
  - platform: numeric_state
    entity_id: sensor.potential_breaking_changes
    above: 0
action:
  service: notify.slack
  data_template:
    message: ""
    target: "#tbsmarthome"
    data:
      attachments:
        - color: >
            #800400
          title: >
            Home Assistant Potential Breaking Changes
          text: |
            " {{ trigger.to_state.attributes.friendly_name }} says a future version has potential breaking changes "
