---
alias: Admin - Home Assistant Started
trigger:
  - platform: homeassistant
    event: start
action:
  - service: notify.slack
    data_template:
      message: ""
      target: "#tbsmarthome"
      data:
        attachments:
          - color: >
              #800400
            title: >
              Home Assistant Started
            text: |
              Home Assistant Started
