---
alias: 'Theme - Startup (Night)'
initial_state: 'true'
trigger:
  - platform: homeassistant
    event: start
condition:
  condition: state
  entity_id: sun.sun
  state: 'below_horizon'
action:
  - service: frontend.set_theme
    data:
      name: dark
