---
alias: Transmission (Torrents) - Torrent Completed
trigger:
  - platform: event
    event_type: transmission_downloaded_torrent
action:
  service: notify.slack
  data_template:
    message: ""
    target: "#tbsmarthome"
    data:
      attachments:
        - color: >
            #800400
          title: >
            Transmission - Torrent Completed
          text: |
            "{{trigger.event.data.name}}"
