---
# ADS-B System / FlightAware

sensor:
  - platform: rest
    name: ADSB FA Feeder
    resource: http://192.168.1.65:8080/status.json
    value_template: '{{ value_json.piaware.status }}'
    method: GET
    scan_interval: 60
    json_attributes:
      - uat_enabled
      - piaware
      - expiry
      - interval
      - mlat
      - modes_enabled
      - adept
      - radio
      - site_url
      - time

  - platform: template
    sensors:
      adsb_fa_adsbfeed:
        friendly_name: Feed
        icon_template: mdi:radar
        value_template: >
          {{ states.sensor.adsb_fa_feeder.attributes["radio"]["status"] }}
        attribute_templates:
          message: >
            {{ states.sensor.adsb_fa_feeder.attributes["radio"]["message"] }}
      adsb_fa_piaware:
        friendly_name: PiAware
        icon_template: mdi:airplane
        value_template: >
          {{ states.sensor.adsb_fa_feeder.attributes["piaware"]["status"] }}
        attribute_templates:
          message: >
            {{ states.sensor.adsb_fa_feeder.attributes["piaware"]["message"] }}
      adsb_fa_flightaware:
        friendly_name: FlightAwaare Feed
        icon_template: mdi:airplane
        value_template: >
          {{ states.sensor.adsb_fa_feeder.attributes["adept"]["status"] }}
        attribute_templates:
          message: >
            {{ states.sensor.adsb_fa_feeder.attributes["adept"]["message"] }}
      adsb_fa_mlat:
        friendly_name: MLAT
        icon_template: mdi:airplane
        value_template: >
          {{ states.sensor.adsb_fa_feeder.attributes["mlat"]["status"] }}
        attribute_templates:
          message: >
            {{ states.sensor.adsb_fa_feeder.attributes["mlat"]["message"] }}