---
sensor:
  ## Weather climatecell.co
  - platform: climacell
    api_key: !secret climacell_apikey
    name: Climacell
    latitude: !secret zone_home_latitude
    longitude: !secret zone_home_longitude
    units: si
    monitored_conditions:
      realtime:
        conditions:
          - temperature
          - feels_like
          - dewpoint
          - humidity
          - wind_speed
          - wind_direction
          - wind_gust
          - pressure
          - precipitation
          - precipitation_type
          #          - precipitation_probability
          #          - precipitation_accumulation
          - sunset
          - sunrise
          - visibility
          - cloud_cover
          - cloud_base
          - cloud_ceiling
          #          - satellite_cloud
          - surface_shortwave_radiation
          - moon_phase
          - weather_condition
          #          - weather_groups
          - pm25
          - pm10
          - o3
          - no2
          - co
          - so2
          - epa_aqi
          - epa_primary_pollutant
          - epa_health_concern
          #          - china_aqi
          #          - china_primary_pollutant
          #          - china_health_concern
          - pollen_tree
          - pollen_weed
          - pollen_grass
          - road_risk_score
          #          - road_risk
          - road_risk_confidence
          - road_risk_conditions
          - fire_index
        update: auto
        scan_interval:
          # At least one of these must be specified:
          days: 0
          hours: 0
          minutes: 30
          seconds: 0
          milliseconds: 0
        exclude_interval:
          1:
            - "23:30"
            - "06:00"
      daily:
        forecast_observations: 1
        conditions:
          - temperature
          - feels_like
          #          - dewpoint
          - humidity
          - wind_speed
          - wind_direction
          #          - wind_gust
          - pressure
          - precipitation
          #          - precipitation_type
          - precipitation_probability
          - precipitation_accumulation
          - sunset
          - sunrise
          - visibility
          #          - cloud_cover
          #          - cloud_base
          #          - cloud_ceiling
          #          - satellite_cloud
          #          - surface_shortwave_radiation
          #          - moon_phase
          - weather_condition
        #          - weather_groups
        #          - pm25
        #          - pm10
        #          - o3
        #          - no2
        #          - co
        #          - so2
        #          - epa_aqi
        #          - epa_primary_pollutant
        #          - epa_health_concern
        #          - china_aqi
        #          - china_primary_pollutant
        #          - china_health_concern
        #          - pollen_tree
        #          - pollen_weed
        #          - pollen_grass
        #          - road_risk_score
        #          - road_risk
        #          - road_risk_confidence
        #          - road_risk_conditions
        #          - fire_index
        scan_interval:
          # At least one of these must be specified:
          days: 0
          hours: 3
          minutes: 0
          seconds: 0
          milliseconds: 0
        exclude_interval:
          1:
            - "10:00"
            - "12:00"
          2:
            - "00:00"
            - "06:30"
      hourly:
        forecast_observations: 1
        conditions:
          - temperature
          - feels_like
          - dewpoint
          - humidity
          - wind_speed
          - wind_direction
          - wind_gust
          - pressure
          - precipitation
          - precipitation_type
          - precipitation_probability
          #          - precipitation_accumulation
          - sunset
          - sunrise
          - visibility
          - cloud_cover
          - cloud_base
          - cloud_ceiling
          #          - satellite_cloud
          - surface_shortwave_radiation
          - moon_phase
          - weather_condition
          #          - weather_groups
          - pm25
          - pm10
          - o3
          - no2
          - co
          - so2
          - epa_aqi
          - epa_primary_pollutant
          - epa_health_concern
          #          - china_aqi
          #          - china_primary_pollutant
          #          - china_health_concern
          - pollen_tree
          - pollen_weed
          - pollen_grass
          - road_risk_score
          #          - road_risk
          - road_risk_confidence
          - road_risk_conditions
        #          - fire_index
        scan_interval:
          # At least one of these must be specified:
          days: 0
          hours: 1
          minutes: 0
          seconds: 0
          milliseconds: 0
        exclude_interval:
          1:
            - "01:00"
            - "05:00"
      nowcast:
        timestep: 5
        forecast_observations: 1
        conditions:
          - temperature
          - feels_like
          - dewpoint
          - humidity
          - wind_speed
          - wind_direction
          - wind_gust
          - pressure
          - precipitation
          - precipitation_type
          #          - precipitation_probability
          #          - precipitation_accumulation
          - sunset
          - sunrise
          - visibility
          - cloud_cover
          - cloud_base
          - cloud_ceiling
          #          - satellite_cloud
          - surface_shortwave_radiation
          #          - moon_phase
          - weather_condition
          #          - weather_groups
          - pm25
          - pm10
          - o3
          - no2
          - co
          - so2
          - epa_aqi
          - epa_primary_pollutant
          - epa_health_concern
          #          - china_aqi
          #          - china_primary_pollutant
          #          - china_health_concern
          - pollen_tree
          - pollen_weed
          - pollen_grass
          - road_risk_score
          #          - road_risk
          - road_risk_confidence
          - road_risk_conditions
        #          - fire_index
        scan_interval:
          # At least one of these must be specified:
          days: 0
          hours: 0
          minutes: 5
          seconds: 0
          milliseconds: 0
        exclude_interval:
          1:
            - "09:00"
            - "10:00"
          2:
            - "13:00"
            - "14:00"
          3:
            - "18:00"
            - "07:00"
