---
sensor:
  - platform: covid19_nswhealth
    name: Tamworth

  - platform: covid19_covidlive
    name: Australia
    region: aus
  - platform: covid19_covidlive
    name: Australian Capital Territory
    region: act
  - platform: covid19_covidlive
    name: New South Wales
    region: nsw
  - platform: covid19_covidlive
    name: Northern Territory
    region: nt
  - platform: covid19_covidlive
    name: Queensland
    region: qld
  - platform: covid19_covidlive
    name: South Australia
    region: sa
  - platform: covid19_covidlive
    name: Tasmania
    region: tas
  - platform: covid19_covidlive
    name: Victoria
    region: vic
  - platform: covid19_covidlive
    name: Western Australia
    region: wa

  - platform: covid19_vaccinelga
    name: LGA
    region: lga

  - platform: rest
    timeout: 60
    scan_interval: 3600
    method: GET
    headers:
      User-Agent: "Home Assistant REST sensor"
    resource: "https://services1.arcgis.com/0MSEUqKaxRlEPj5g/arcgis/rest/services/ncov_cases/FeatureServer/1/query?f=json&where=(Confirmed%20%3E%200)%20AND%20(Province_State%3D%27New South Wales%27)&returnGeometry=false&spatialRel=esriSpatialRelIntersects&outFields=*&orderByFields=Confirmed%20desc%2CCountry_Region%20asc%2CProvince_State%20asc&outSR=102100&resultOffset=0&resultRecordCount=250&cacheHint=true"
    name: "Coronavirus NSW"
    value_template: >-
      {{ value_json.features[0].attributes.Confirmed }}
    json_attributes_path: "$.features[0].attributes"
    json_attributes:
      - Confirmed
      - Deaths
      - Recovered
      - Active
      - Last_Update
    unit_of_measurement: "People"

  - platform: template
    sensors:
      covid_19_nswh_local_pct:
        friendly_name: "COVID-19 NSWH Local Percents"
        unit_of_measurement: "%"
        icon_template: mdi:biohazard
        value_template: >
          {% set val = state_attr('sensor.covid_19_nswh_local', 'hneh') %}
          {% if val == 0 %}
            {{ 0 }}
          {% else %}
            {{ (((val|int)/912352)*100)|round(3) }}
          {% endif %}
        attribute_templates:
          hneh_percent: >
            {% set val = state_attr('sensor.covid_19_nswh_local', 'hneh') %}
            {% if val == 0 %}
              {{ 0 }}
            {% else %}
              {{ (((val|int)/912352)*100)|round(3) }}
            {% endif %}
          trc_percent: >
            {% set val = state_attr('sensor.covid_19_nswh_local', 'trc') %}
            {% if val == 0 %}
              {{ 0 }}
            {% else %}
              {{ (((val|int)/62156)*100)|round(3) }}
            {% endif %}
          tamw_percent: >
            {% set val = state_attr('sensor.covid_19_nswh_local', 'tamw') %}
            {% if val == 0 %}
              {{ 0 }}
            {% else %}
              {{ (((val|int)/49072)*100)|round(3) }}
            {% endif %}
          hneh_percent_cases: >
            {% set val = state_attr('sensor.covid_19_nswh_local', 'hneh') %}
            {% set val2 = state_attr('sensor.covid_19_covidlive_nsw', 'Cases') %}
            {% if val == 0 or val2 == 0 %}
              {{ 0 }}
            {% else %}
              {{ (((val|int)/(state_attr('sensor.covid_19_covidlive_nsw', 'Cases')|int))*100)|round(3) }}
            {% endif %}
          trc_percent_cases: >
            {% set val = state_attr('sensor.covid_19_nswh_local', 'trc') %}
            {% set val2 = state_attr('sensor.covid_19_covidlive_nsw', 'Cases') %}
            {% if val == 0 or val2 == 0 %}
              {{ 0 }}
            {% else %}
              {{ (((val|int)/(state_attr('sensor.covid_19_covidlive_nsw', 'Cases')|int))*100)|round(3) }}
            {% endif %}
          tamw_percent_cases: >
            {% set val = state_attr('sensor.covid_19_nswh_local', 'tamw') %}
            {% set val2 = state_attr('sensor.covid_19_covidlive_nsw', 'Cases') %}
            {% if val == 0 or val2 == 0 %}
              {{ 0 }}
            {% else %}
              {{ (((val|int)/(val2|int))*100)|round(3) }}
            {% endif %}
          wnsw_percent: >
            {% set val = state_attr('sensor.covid_19_nswh_local', 'wnsw') %}
            {% if val == 0 %}
              {{ 0 }}
            {% else %}
              {{ (((val|int)/279422)*100)|round(3) }}
            {% endif %}
          drc_percent: >
            {% set val = state_attr('sensor.covid_19_nswh_local', 'drc') %}
            {% if val == 0 %}
              {{ 0 }}
            {% else %}
              {{ (((val|int)/52445)*100)|round(3) }}
            {% endif %}
          dubo_percent: >
            {% set val = state_attr('sensor.covid_19_nswh_local', 'dubo') %}
            {% if val == 0 %}
              {{ 0 }}
            {% else %}
              {{ (((val|int(default=0))/38943)*100)|round(3) }}
            {% endif %}
          wnsw_percent_cases: >
            {% set val = state_attr('sensor.covid_19_nswh_local', 'wnsw') %}
            {% set val2 = state_attr('sensor.covid_19_covidlive_nsw', 'Cases') %}
            {% if val == 0 or val2 == 0 %}
              {{ 0 }}
            {% else %}
              {{ (((val|int(default=0))/(state_attr('sensor.covid_19_covidlive_nsw', 'Cases')|int(default=0)))*100)|round(3) }}
            {% endif %}
          drc_percent_cases: >
            {% set val = state_attr('sensor.covid_19_nswh_local', 'drc') %}
            {% set val2 = state_attr('sensor.covid_19_covidlive_nsw', 'Cases') %}
            {% if val == 0 or val2 == 0 %}
              {{ 0 }}
            {% else %}
              {{ (((val|int(default=0))/(state_attr('sensor.covid_19_covidlive_nsw', 'Cases')|int(default=0)))*100)|round(3) }}
            {% endif %}
          dubo_percent_cases: >
            {% set val = state_attr('sensor.covid_19_nswh_local', 'dubo') %}
            {% set val2 = state_attr('sensor.covid_19_covidlive_nsw', 'Cases') %}
            {% if val == 0 or val2 == 0 %}
              {{ 0 }}
            {% else %}
              {{ (((val|int(default=0))/(val2|int))*100)|round(3) }}
            {% endif %}

      covid_19_covidlive_aus_vaccines:
        friendly_name: "COVID-19 Covidlive AUS Vaccines"
        value_template: >
          {{ (state_attr('sensor.covid_19_covidlive_aus', 'Doses')|int(default=0))
          - ((state_attr('sensor.covid_19_covidlive_act', 'Doses')|int(default=0))
          + (state_attr('sensor.covid_19_covidlive_nsw', 'Doses')|int(default=0))
          + (state_attr('sensor.covid_19_covidlive_vic', 'Doses')|int(default=0))
          + (state_attr('sensor.covid_19_covidlive_qld', 'Doses')|int(default=0))
          + (state_attr('sensor.covid_19_covidlive_tas', 'Doses')|int(default=0))
          + (state_attr('sensor.covid_19_covidlive_sa', 'Doses')|int(default=0))
          + (state_attr('sensor.covid_19_covidlive_nt', 'Doses')|int(default=0))
          + (state_attr('sensor.covid_19_covidlive_wa', 'Doses')|int(default=0)))
          }}
        unit_of_measurement: Doses
        icon_template: mdi:biohazard
      covid_19_covidlive_aus_vaccines_1stdose:
        friendly_name: "COVID-19 Covidlive AUS Vaccines 1st Dose"
        value_template: >
          {{ (state_attr('sensor.covid_19_covidlive_aus', 'Doses1st')|int)
          - ((state_attr('sensor.covid_19_covidlive_act', 'Doses1st')|int)
          + (state_attr('sensor.covid_19_covidlive_nsw', 'Doses1st')|int)
          + (state_attr('sensor.covid_19_covidlive_vic', 'Doses1st')|int)
          + (state_attr('sensor.covid_19_covidlive_qld', 'Doses1st')|int)
          + (state_attr('sensor.covid_19_covidlive_tas', 'Doses1st')|int)
          + (state_attr('sensor.covid_19_covidlive_sa', 'Doses1st')|int)
          + (state_attr('sensor.covid_19_covidlive_nt', 'Doses1st')|int)
          + (state_attr('sensor.covid_19_covidlive_wa', 'Doses1st')|int))
          }}
        unit_of_measurement: Doses
        icon_template: mdi:biohazard
      covid_19_covidlive_aus_vaccines_2nddose:
        friendly_name: "COVID-19 Covidlive AUS Vaccines 2nd Dose"
        value_template: >
          {{ (state_attr('sensor.covid_19_covidlive_aus', 'Doses2nd')|int(default=0))
          - ((state_attr('sensor.covid_19_covidlive_act', 'Doses2nd')|int(default=0))
          + (state_attr('sensor.covid_19_covidlive_nsw', 'Doses2nd')|int(default=0))
          + (state_attr('sensor.covid_19_covidlive_vic', 'Doses2nd')|int(default=0))
          + (state_attr('sensor.covid_19_covidlive_qld', 'Doses2nd')|int(default=0))
          + (state_attr('sensor.covid_19_covidlive_tas', 'Doses2nd')|int(default=0))
          + (state_attr('sensor.covid_19_covidlive_sa', 'Doses2nd')|int(default=0))
          + (state_attr('sensor.covid_19_covidlive_nt', 'Doses2nd')|int(default=0))
          + (state_attr('sensor.covid_19_covidlive_wa', 'Doses2nd')|int(default=0)))
          }}
        unit_of_measurement: Doses
        icon_template: mdi:biohazard
      covid_19_covidlive_vac_pct:
        friendly_name: "COVID-19 Covidlive Vaccine Percents"
        unit_of_measurement: "%"
        icon_template: mdi:biohazard
        value_template: >
          {{ (((state_attr('sensor.covid_19_covidlive_aus', 'Doses')|int(default=0))/25687000)*100)|round(3) }}
        attribute_templates:
          act_poppct: >
            {{ (((state_attr('sensor.covid_19_covidlive_act', 'Doses')|int(default=0))/431100)*100)|round(3) }}
          nsw_poppct: >
            {{ (((state_attr('sensor.covid_19_covidlive_nsw', 'Doses')|int(default=0))/8164100)*100)|round(3) }}
          nt_poppct: >
            {{ (((state_attr('sensor.covid_19_covidlive_nt', 'Doses')|int(default=0))/246000)*100)|round(3) }}
          qld_poppct: >
            {{ (((state_attr('sensor.covid_19_covidlive_qld', 'Doses')|int(default=0))/5174400)*100)|round(3) }}
          sa_poppct: >
            {{ (((state_attr('sensor.covid_19_covidlive_sa', 'Doses')|int(default=0))/1769300)*100)|round(3) }}
          tas_poppct: >
            {{ (((state_attr('sensor.covid_19_covidlive_tas', 'Doses')|int(default=0))/540600)*100)|round(3) }}
          vic_poppct: >
            {{ (((state_attr('sensor.covid_19_covidlive_vic', 'Doses')|int(default=0))/6694900)*100)|round(3) }}
          wa_poppct: >
            {{ (((state_attr('sensor.covid_19_covidlive_wa', 'Doses')|int(default=0))/2661900)*100)|round(3) }}
