---
sensor:
  - platform: rest
    name: Hass Main config
    resource: !secret hass_api_config_url
    authentication: basic
    value_template: >
      {{ value_json.version }}
    json_attributes:
      - components
      - unit_system
      - config_dir
      - version
    headers:
      Content-Type: application/json
      Authorization: !secret ha_api_llat
      User-Agent: Home Assistant REST sensor

  - platform: rest
    name: Hass.io Info
    resource: !secret hassio_api_info_url
    authentication: basic
    value_template: >
      {{ value_json.result }}
    json_attributes:
      - data
    headers:
      Content-Type: application/json
      Authorization: !secret ha_api_llat
      User-Agent: Home Assistant REST sensor

  - platform: rest
    name: hassos_installed_version
    resource: !secret hassio_api_info_url
    authentication: basic
    value_template: >
      {{ value_json.data.hassos }}
    headers:
      Content-Type: application/json
      Authorization: !secret ha_api_llat
      User-Agent: Home Assistant REST sensor

  - platform: template
    sensors:
      count_all_components:
        friendly_name: "All Components"
        icon_template: mdi:code-tags
        value_template: "{{ states.sensor.hass_main_config.attributes.components | count }}"

binary_sensor:
  - platform: template
    sensors:
      ha_update_available:
        friendly_name: "HA Update Available"
        icon_template: mdi:home-assistant
        value_template: >-
          {{ states('sensor.ha_latest_version') != 'unavailable' and states('sensor.ha_latest_version') > states('sensor.ha_current_version') }}

# http://192.168.1.62:8123/api/supervisor/info
# http://192.168.1.62:8123/api/hassio/snapshots
# http://192.168.1.62:8123/api/hassio/info

rest:
  - resource: https://version.home-assistant.io/beta.json
    scan_interval: 600
    sensor:
      - name: ha_version_beta
        json_attributes:
          - supervisor
          - homeassistant
          - hassos
          - cli
          - dns
          - audio
          - multicast
          - observer
        value_template: "OK"
  - resource: https://version.home-assistant.io/dev.json
    scan_interval: 600
    sensor:
      - name: ha_version_dev
        json_attributes:
          - supervisor
          - homeassistant
          - hassos
          - cli
          - dns
          - audio
          - multicast
          - observer
        value_template: "OK"
