---
sensor:
  - platform: mqtt
    icon: mdi:solar-power
    name: sungrowsolar_alldata
    state_topic: solar/inverter_SG5KD/SENSOR
    value_template: "{{value_json.daily_power_yields|float(default=0)}}"
    unit_of_measurement: "kW"
    json_attributes_topic: solar/inverter_SG5KD/SENSOR
  - platform: integration
    source: sensor.sungrowsolar_solar_production
    name: SungrowSolar Solar Production (kWh)
  - platform: integration
    source: sensor.sungrowsolar_return_to_grid
    name: SungrowSolar Returned to Grid (kWh)
  - platform: integration
    source: sensor.sungrowsolar_import_from_grid
    name: SungrowSolar Grid Consumption (kWh)

template:
  - sensor:
      - name: "sungrowsolar_solar_production"
        unique_id: sungrowsolar_solar_production
        unit_of_measurement: "kW"
        device_class: power
        state: >
          {{ ( state_attr('sensor.sungrowsolar_alldata', 'total_active_power') | float(default=0) ) / (1000) }}
      - name: "sungrowsolar_return_to_grid"
        unique_id: sungrowsolar_return_to_grid
        unit_of_measurement: "kW"
        device_class: power
        state: >
          {{ ( state_attr('sensor.sungrowsolar_alldata', 'export_to_grid') | float(default=0) ) / (1000) }}
      - name: "sungrowsolar_import_from_grid"
        unique_id: sungrowsolar_import_from_grid
        unit_of_measurement: "kW"
        device_class: power
        state: >
          {{ ( state_attr('sensor.sungrowsolar_alldata', 'import_from_grid') | float(default=0) ) / (1000) }}
      - name: "sungrowsolar_load_power"
        unique_id: sungrowsolar_load_power
        unit_of_measurement: "kW"
        device_class: power
        state: >
          {{ ( state_attr('sensor.sungrowsolar_alldata', 'load_power') | float(default=0) ) / (1000) }}
      - name: "sungrowsolar_export_to_grid"
        unique_id: sungrowsolar_export_to_grid
        unit_of_measurement: "kW"
        device_class: power
        state: >
          {{ -( state_attr('sensor.sungrowsolar_alldata', 'export_to_grid') | float(default=0) ) / (1000) }}
      - name: "sungrowsolar_daily_power_yields"
        unique_id: sungrowsolar_daily_power_yields
        unit_of_measurement: "kWh"
        device_class: energy
        state: >
          {{ ( state_attr('sensor.sungrowsolar_alldata', 'daily_power_yields') | float(default=0) ) }}
      - name: "sungrowsolar_daily_export_energy"
        unique_id: sungrowsolar_daily_export_energy
        unit_of_measurement: "kWh"
        device_class: energy
        state: >
          {{ ( state_attr('sensor.sungrowsolar_alldata', 'daily_export_energy') | float(default=0) ) }}
      - name: "sungrowsolar_daily_import_energy"
        unique_id: sungrowsolar_daily_import_energy
        unit_of_measurement: "kWh"
        device_class: energy
        state: >
          {{ ( state_attr('sensor.sungrowsolar_alldata', 'daily_import_energy') | float(default=0) ) }}
      - name: "sungrowsolar_daily_direct_energy_consumption"
        unique_id: sungrowsolar_daily_direct_energy_consumption
        unit_of_measurement: "kWh"
        device_class: energy
        state: >
          {{ ( state_attr('sensor.sungrowsolar_alldata', 'daily_direct_energy_consumption') | float(default=0) ) }}
      - name: sungrowsolar_runtime
        unique_id: sungrowsolar_runtime
        state: >
          {%- set time = state_attr('sensor.sungrowsolar_alldata', 'daily_running_time') | int(default=0) * 60 %}
          {%- set minutes = ((time % 3600) // 60) %}
          {%- set minutes = '{}min'.format(minutes) if minutes > 0 else '' %}
          {%- set hours = ((time % 86400) // 3600) %}
          {%- set hours = '{}hr '.format(hours) if hours > 0 else '' %}
          {%- set days = (time // 86400) %}
          {%- set days = '{}d '.format(days) if days > 0 else '' %}
          {{ 'Less than 1 min' if time < 60 else days + hours + minutes }}
