---
sensor:
  - platform: template
    sensors:
      # Manchester United
      sport_manu:
        friendly_name: Manchester United
        entity_picture_template: /local/sportlogos/manu.png
        value_template: >-
          {% set op = state_attr('calendar.manchester_united_fixtures', 'message') %}
          {% if is_state('calendar.manchester_united_fixtures', 'on') %}
            Playing Now - {{ op }}
          {% else %}
            {% set st = state_attr('calendar.manchester_united_fixtures', 'start_time') %}
            {% if st != None %}
              {% set diff = ((as_timestamp(st)-as_timestamp(now())) | int /60/1440) | round (0) %}
              {% if diff > 6 %}
                {{ diff }} Days - {{ op }}
              {% else %}
                {{ as_timestamp(st) | timestamp_custom("%a %H:%M") }} - {{ op }}
              {% endif %}
            {% else %}
              No Game Scheduled
            {% endif %}
          {% endif %}

      sport_newengpats:
        friendly_name: New England Patriots
        entity_picture_template: /local/sportlogos/newengpats.png
        value_template: >-
          {% set op = state_attr('calendar.new_england_patriots', 'message') %}
          {% if is_state('calendar.new_england_patriots', 'on') %}
            Playing Now - {{ op }}
          {% else %}
            {% set st = state_attr('calendar.new_england_patriots', 'start_time') %}
            {% if st != None %}
              {% set diff = ((as_timestamp(st)-as_timestamp(now())) | int /60/1440) | round (0) %}
              {% if diff > 6 %}
                {{ diff }} Days - {{ op }}
              {% else %}
                {{ as_timestamp(st) | timestamp_custom("%a %H:%M") }} - {{ op }}
              {% endif %}
            {% else %}
              No Game Scheduled
            {% endif %}
          {% endif %}

      sport_anaducks:
        friendly_name: Anaheim (Mighty) Ducks
        entity_picture_template: /local/sportlogos/Anaheim_Ducks.svg
        value_template: >-
          {% set op = state_attr('calendar.anaheim_ducks', 'message') %}
          {% if is_state('calendar.anaheim_ducks', 'on') %}
            Playing Now - {{ op }}
          {% else %}
            {% set st = state_attr('calendar.anaheim_ducks', 'start_time') %}
            {% if st != None %}
              {% set diff = ((as_timestamp(st)-as_timestamp(now())) | int /60/1440) | round (0) %}
              {% if diff > 6 %}
                {{ diff }} Days - {{ op }}
              {% else %}
                {{ as_timestamp(st) | timestamp_custom("%a %H:%M") }} - {{ op }}
              {% endif %}
            {% else %}
              No Game Scheduled
            {% endif %}
          {% endif %}

      # New York Yankees
      sport_yankees:
        friendly_name: New York Yankees
        entity_picture_template: /local/sportlogos/yankees.png
        value_template: >-
          {% set op = state_attr('calendar.new_york_yankees', 'message') | replace('âš¾ï¸ ','') %}
          {% if is_state('calendar.new_york_yankees', 'on') %}
            Playing Now - {{ op }}
          {% else %}
            {% set st = state_attr('calendar.new_york_yankees', 'start_time') %}
            {% if st != None %}
              {% set diff = ((as_timestamp(st)-as_timestamp(now())) | int /60/1440) | round (0) %}
              {% if diff > 6 %}
                {{ diff }} Days - {{ op }}
              {% else %}
                {{ as_timestamp(st) | timestamp_custom("%a %H:%M") }} - {{ op }}
              {% endif %}
            {% else %}
              No Game Scheduled
            {% endif %}
          {% endif %}

      # Cricket
      sport_cricket:
        friendly_name: Cricket Australia (Aus/Syd6ers)
        entity_picture_template: /local/sportlogos/cricket.png
        value_template: >-
          {% set op = state_attr('calendar.cricket_australia', 'message') %}
          {% if is_state('calendar.cricket_australia', 'on') %}
            Playing Now - {{ op }}
          {% else %}
            {% set st = state_attr('calendar.cricket_australia', 'start_time') %}
            {% if st != None %}
              {% set diff = ((as_timestamp(st)-as_timestamp(now())) | int /60/1440) | round (0) %}
              {% if diff > 6 %}
                {{ diff }} Days - {{ op }}
              {% else %}
                {{ as_timestamp(st) | timestamp_custom("%a %H:%M") }} - {{ op }}
              {% endif %}
            {% else %}
              No Match Scheduled
            {% endif %}
          {% endif %}

      # Supercars
      sport_supercars:
        friendly_name: Supercars
        entity_picture_template: /local/sportlogos/supercars.png
        value_template: >-
          {% set op = state_attr('calendar.supercars', 'message') | replace('SUPERCARS: ','') %}
          {% if is_state('calendar.supercars', 'on') %}
            Today - {{ op }}
          {% else %}
            {% set st = state_attr('calendar.supercars', 'start_time') %}
            {% if st != None %}
              {% set diff = ((as_timestamp(st)-as_timestamp(now())) | int /60/1440) | round (0) %}
              {% if diff > 6 %}
                {{ diff }} Days - {{ op }}
              {% else %}
                {{ as_timestamp(st) | timestamp_custom("%a %H:%M") }} - {{ op }}
              {% endif %}
            {% else %}
              No Race Scheduled
            {% endif %}
          {% endif %}

      # F1
      sport_f1:
        friendly_name: Formula One
        entity_picture_template: /local/sportlogos/F1.svg
        value_template: >-
          {% set op = state_attr('calendar.f1', 'message') %}
          {% if is_state('calendar.f1', 'on') %}
            Today - {{ op }}
          {% else %}
            {% set st = state_attr('calendar.f1', 'start_time') %}
            {% if st != None %}
              {% set diff = ((as_timestamp(st)-as_timestamp(now())) | int /60/1440) | round (0) %}
              {% if diff > 6 %}
                {{ diff }} Days - {{ op }}
              {% else %}
                {{ as_timestamp(st) | timestamp_custom("%a %H:%M") }} - {{ op }}
              {% endif %}
            {% else %}
              No Race Scheduled
            {% endif %}
          {% endif %}

      sport_wec:
        friendly_name: FIA WEC
        entity_picture_template: /local/sportlogos/wec.png
        value_template: >-
          {% set op = state_attr('calendar.lm_wec_fia_world_endurance_championship', 'message') | replace('FIA WEC ', '') %}
          {% if is_state('calendar.lm_wec_fia_world_endurance_championship', 'on') %}
            Today - {{ op }}
          {% else %}
            {% set st = state_attr('calendar.lm_wec_fia_world_endurance_championship', 'start_time') %}
            {% if st != None %}
              {% set diff = ((as_timestamp(st)-as_timestamp(now())) | int /60/1440) | round (0) %}
              {% if diff > 6 %}
                {{ diff }} Days - {{ op }}
              {% else %}
                {{ as_timestamp(st) | timestamp_custom("%a %H:%M") }} - {{ op }}
              {% endif %}
            {% else %}
              No Race Scheduled
            {% endif %}
          {% endif %}

      # Nascar
      sport_nascar_cup:
        friendly_name: NASCAR Cup Series
        entity_picture_template: /local/sportlogos/nascarcup.png
        value_template: >-
          {% set op = state_attr('calendar.nascar_cup_series', 'message') | replace('NASCAR Cup ', '') %}
          {% if is_state('calendar.nascar_cup_series', 'on') %}
            Today - {{ op }}
          {% else %}
            {% set st = state_attr('calendar.nascar_cup_series', 'start_time') %}
            {% if st != None %}
              {% set diff = ((as_timestamp(st)-as_timestamp(now())) | int /60/1440) | round (0) %}
              {% if diff > 6 %}
                {{ diff }} Days - {{ op }}
              {% else %}
                {{ as_timestamp(st) | timestamp_custom("%a %H:%M") }} - {{ op }}
              {% endif %}
            {% else %}
              No Race Scheduled
            {% endif %}
          {% endif %}

      sport_nascar_xfinity:
        friendly_name: NASCAR Xfinity Series
        entity_picture_template: /local/sportlogos/nascarxfinity.png
        value_template: >-
          {% set op = state_attr('calendar.nascar_xfinity_series', 'message') | replace('NASCAR Xfinity ', '') %}
          {% if is_state('calendar.nascar_xfinity_series', 'on') %}
            Today - {{ op }}
          {% else %}
            {% set st = state_attr('calendar.nascar_xfinity_series', 'start_time') %}
            {% if st != None %}
              {% set diff = ((as_timestamp(st)-as_timestamp(now())) | int /60/1440) | round (0) %}
              {% if diff > 6 %}
                {{ diff }} Days - {{ op }}
              {% else %}
                {{ as_timestamp(st) | timestamp_custom("%a %H:%M") }} - {{ op }}
              {% endif %}
            {% else %}
              No Race Scheduled
            {% endif %}
          {% endif %}

      # Indycar
      sport_indycar:
        friendly_name: IndyCar
        entity_picture_template: /local/sportlogos/indycar.png
        value_template: >-
          {% set op = state_attr('calendar.indycar', 'message') | replace('ðŸ ', '') %}
          {% if is_state('calendar.indycar', 'on') %}
            Today - {{ op }}
          {% else %}
            {% set st = state_attr('calendar.indycar', 'start_time') %}
            {% if st != None %}
              {% set diff = ((as_timestamp(st)-as_timestamp(now())) | int /60/1440) | round (0) %}
              {% if diff > 6 %}
                {{ diff }} Days - {{ op }}
              {% else %}
                {{ as_timestamp(st) | timestamp_custom("%a %H:%M") }} - {{ op }}
              {% endif %}
            {% else %}
              No Race Scheduled
            {% endif %}
          {% endif %}

      # Newcastle Knights
      sport_newknights:
        friendly_name: Newcastle Knights
        entity_picture_template: /local/sportlogos/newknights.svg
        value_template: >-
          {% set op = state_attr('calendar.newcastle_knights', 'message') %}
          {% if is_state('calendar.newcastle_knights', 'on') %}
            Playing Now - {{ op }}
          {% else %}
            {% set st = state_attr('calendar.newcastle_knights', 'start_time') %}
            {% if st != None %}
              {% set diff = ((as_timestamp(st)-as_timestamp(now())) | int /60/1440) | round (0) %}
              {% if diff > 6 %}
                {{ diff }} Days - {{ op }}
              {% else %}
                {{ as_timestamp(st) | timestamp_custom("%a %H:%M") }} - {{ op }}
              {% endif %}
            {% else %}
              No Game Scheduled
            {% endif %}
          {% endif %}

      sport_sydfc:
        friendly_name: Sydney FC
        entity_picture_template: /local/sportlogos/sydfc.png
        value_template: >-
          {% set op = state_attr('calendar.sydney_fc', 'message') | replace ('âš½ï¸ ', '') %}
          {% if is_state('calendar.sydney_fc', 'on') %}
            Playing Now - {{ op }}
          {% else %}
            {% set st = state_attr('calendar.sydney_fc', 'start_time') %}
            {% if st != None %}
              {% set diff = ((as_timestamp(st)-as_timestamp(now())) | int /60/1440) | round (0) %}
              {% if diff > 6 %}
                {{ diff }} Days - {{ op }}
              {% else %}
                {{ as_timestamp(st) | timestamp_custom("%a %H:%M") }} - {{ op }}
              {% endif %}
            {% else %}
              No Game Scheduled
            {% endif %}
          {% endif %}

      sport_sydswans:
        friendly_name: Sydney Swans
        entity_picture_template: /local/sportlogos/sydswans.png
        value_template: >-
          {% set op = state_attr('calendar.sydney_swans', 'message') %}
          {% if is_state('calendar.sydney_swans', 'on') %}
            Playing Now - {{ op }}
          {% else %}
            {% set st = state_attr('calendar.sydney_swans', 'start_time') %}
            {% if st != None %}
              {% set diff = ((as_timestamp(st)-as_timestamp(now())) | int /60/1440) | round (0) %}
              {% if diff > 6 %}
                {{ diff }} Days - {{ op }}
              {% else %}
                {{ as_timestamp(st) | timestamp_custom("%a %H:%M") }} - {{ op }}
              {% endif %}
            {% else %}
              No Game Scheduled
            {% endif %}
          {% endif %}

      sport_nswwaratahs:
        friendly_name: NSW Waratahs
        entity_picture_template: /local/sportlogos/nswaratahs.png
        value_template: >-
          {% set op = state_attr('calendar.nsw_waratahs', 'message') %}
          {% if is_state('calendar.nsw_waratahs', 'on') %}
            Playing Now - {{ op }}
          {% else %}
            {% set st = state_attr('calendar.nsw_waratahs', 'start_time') %}
            {% if st != None %}
              {% set diff = ((as_timestamp(st)-as_timestamp(now())) | int /60/1440) | round (0) %}
              {% if diff > 6 %}
                {{ diff }} Days - {{ op }}
              {% else %}
                {{ as_timestamp(st) | timestamp_custom("%a %H:%M") }} - {{ op }}
              {% endif %}
            {% else %}
              No Game Scheduled
            {% endif %}
          {% endif %}

      sport_btcc:
        friendly_name: BTCC
        entity_picture_template: /local/sportlogos/btcc.png
        value_template: >-
          {% set op = state_attr('calendar.btcc', 'message') | replace('BTCC ', '') %}
          {% if is_state('calendar.btcc', 'on') %}
            Today - {{ op }}
          {% else %}
            {% set st = state_attr('calendar.btcc', 'start_time') %}
            {% if st != None %}
              {% set diff = ((as_timestamp(st)-as_timestamp(now())) | int /60/1440) | round (0) %}
              {% if diff > 6 %}
                {{ diff }} Days - {{ op }}
              {% else %}
                {{ as_timestamp(st) | timestamp_custom("%a %H:%M") }} - {{ op }}
              {% endif %}
            {% else %}
              No Race Scheduled
            {% endif %}
          {% endif %}
      sport_icgtc:
        friendly_name: Intercontinental GT Challenge
        entity_picture_template: /local/sportlogos/icgtc.png
        value_template: >-
          {% set op = state_attr('calendar.gt_intercontinental_gt_challenge', 'message') | replace('BTCC ', '') %}
          {% if is_state('calendar.gt_intercontinental_gt_challenge', 'on') %}
            Today - {{ op }}
          {% else %}
            {% set st = state_attr('calendar.gt_intercontinental_gt_challenge', 'start_time') %}
            {% if st != None %}
              {% set diff = ((as_timestamp(st)-as_timestamp(now())) | int /60/1440) | round (0) %}
              {% if diff > 6 %}
                {{ diff }} Days - {{ op }}
              {% else %}
                {{ as_timestamp(st) | timestamp_custom("%a %H:%M") }} - {{ op }}
              {% endif %}
            {% else %}
              No Race Scheduled
            {% endif %}
          {% endif %}
      sport_imsasports:
        friendly_name: IMSA SportsCar Championship
        entity_picture_template: /local/sportlogos/imsasc.png
        value_template: >-
          {% set op = state_attr('calendar.imsa_weathertech_sportscar_championship', 'message') | replace('IMSA WeatherTech Championship ', '') %}
          {% if is_state('calendar.imsa_weathertech_sportscar_championship', 'on') %}
            Today - {{ op }}
          {% else %}
            {% set st = state_attr('calendar.imsa_weathertech_sportscar_championship', 'start_time') %}
            {% if st != None %}
              {% set diff = ((as_timestamp(st)-as_timestamp(now())) | int /60/1440) | round (0) %}
              {% if diff > 6 %}
                {{ diff }} Days - {{ op }}
              {% else %}
                {{ as_timestamp(st) | timestamp_custom("%a %H:%M") }} - {{ op }}
              {% endif %}
            {% else %}
              No Race Scheduled
            {% endif %}
          {% endif %}
      sport_motogp:
        friendly_name: MotoGP
        entity_picture_template: /local/sportlogos/motogp.png
        value_template: >-
          {% set op = state_attr('calendar.motogp', 'message') | replace('MotoGP ', '') %}
          {% if is_state('calendar.motogp', 'on') %}
            Today - {{ op }}
          {% else %}
            {% set st = state_attr('calendar.motogp', 'start_time') %}
            {% if st != None %}
              {% set diff = ((as_timestamp(st)-as_timestamp(now())) | int /60/1440) | round (0) %}
              {% if diff > 6 %}
                {{ diff }} Days - {{ op }}
              {% else %}
                {{ as_timestamp(st) | timestamp_custom("%a %H:%M") }} - {{ op }}
              {% endif %}
            {% else %}
              No Race Scheduled
            {% endif %}
          {% endif %}
      sport_wrc:
        friendly_name: World Rally Championship
        entity_picture_template: /local/sportlogos/wrc.png
        value_template: >-
          {% set op = state_attr('calendar.wrc', 'message') | replace('WRC ', '') %}
          {% if is_state('calendar.wrc', 'on') %}
            Today - {{ op }}
          {% else %}
            {% set st = state_attr('calendar.wrc', 'start_time') %}
            {% if st != None %}
              {% set diff = ((as_timestamp(st)-as_timestamp(now())) | int /60/1440) | round (0) %}
              {% if diff > 6 %}
                {{ diff }} Days - {{ op }}
              {% else %}
                {{ as_timestamp(st) | timestamp_custom("%a %H:%M") }} - {{ op }}
              {% endif %}
            {% else %}
              No Race Scheduled
            {% endif %}
          {% endif %}
      sport_dtm:
        friendly_name: DTM
        entity_picture_template: /local/sportlogos/dtm.png
        value_template: >-
          {% set op = state_attr('calendar.dtm', 'message') | replace('DTM ', '') %}
          {% if is_state('calendar.dtm', 'on') %}
            Today - {{ op }}
          {% else %}
            {% set st = state_attr('calendar.dtm', 'start_time') %}
            {% if st != None %}
              {% set diff = ((as_timestamp(st)-as_timestamp(now())) | int /60/1440) | round (0) %}
              {% if diff > 6 %}
                {{ diff }} Days - {{ op }}
              {% else %}
                {{ as_timestamp(st) | timestamp_custom("%a %H:%M") }} - {{ op }}
              {% endif %}
            {% else %}
              No Race Scheduled
            {% endif %}
          {% endif %}
      sport_formula_e:
        friendly_name: Formula E
        entity_picture_template: /local/sportlogos/formulae.png
        value_template: >-
          {% set op = state_attr('calendar.fia_formula_e', 'message') | replace('FE - ', '') %}
          {% if is_state('calendar.fia_formula_e', 'on') %}
            Today - {{ op }}
          {% else %}
            {% set st = state_attr('calendar.fia_formula_e', 'start_time') %}
            {% if st != None %}
              {% set diff = ((as_timestamp(st)-as_timestamp(now())) | int /60/1440) | round (0) %}
              {% if diff > 6 %}
                {{ diff }} Days - {{ op }}
              {% else %}
                {{ as_timestamp(st) | timestamp_custom("%a %H:%M") }} - {{ op }}
              {% endif %}
            {% else %}
              No Race Scheduled
            {% endif %}
          {% endif %}
