---
homeassistant:
  customize:
    sensor.waqi_tamworth_min_aqi:
      friendly_name: "Min AQI (Last 24hrs)"
      icon: mdi:chart-bubble
      unit_of_measurement: "AQI"
    sensor.waqi_tamworth_max_aqi:
      friendly_name: "Max AQI (Last 24hrs)"
      icon: mdi:chart-bubble
      unit_of_measurement: "AQI"

    sensor.waqi_tamworth_change_aqi:
      friendly_name: "AQI Change (Last 24hrs)"
      icon: mdi:chart-bubble
      unit_of_measurement: "AQI"

sensor:
  - platform: statistics
    name: waqi_tamworth_min_aqi
    state_characteristic: value_min
    sampling_size: 150
    entity_id: sensor.waqi_tamworth_north_west_slopes
    max_age:
      hours: 24

  - platform: statistics
    name: waqi_tamworth_max_aqi
    state_characteristic: value_max
    sampling_size: 150
    entity_id: sensor.waqi_tamworth_north_west_slopes
    max_age:
      hours: 24

  - platform: statistics
    name: waqi_tamworth_change_aqi
    state_characteristic: change
    sampling_size: 150
    entity_id: sensor.waqi_tamworth_north_west_slopes
    max_age:
      hours: 24
