---
binary_sensor:
  - name: "[Weather] High Temperature Alert"
    unique_id: weather_high_temperature_alert
    delay_on: 900
    delay_off: 900
    state: >
      {{ states('sensor.weather_temperature')|int
            > states('input_number.high_temperature_threshold')|int
          and is_state('input_boolean.alerts_weather','on') }}
    availability: "{{ is_number(states('sensor.weather_temperature')) }}"
    attributes:
      category: weather_alert

  - name: "[Weather] Low Temperature Alert"
    unique_id: weather_low_temperature_alert
    delay_on: 900
    delay_off: 900
    state: >
      {{ states('sensor.weather_temperature')|int
            < states('input_number.low_temperature_threshold')|int
          and is_state('input_boolean.alerts_weather','on') }}
    availability: "{{ is_number(states('sensor.weather_temperature')) }}"
    attributes:
      category: weather_alert

  - name: "[Weather] Rain Alert"
    unique_id: weather_rain_alert
    delay_on: 30
    delay_off: 30
    state: >
      {{is_state('binary_sensor.weatherflow_is_raining','on')
        and states('sensor.weather_precipitation_today') > 0.02
        and is_state('input_boolean.alerts_weather','on') }}
    availability: "{{ is_number(states('sensor.weather_precipitation_today')) }}"
    attributes:
      category: weather_alert

  - name: "[Weather] Temperature Alert"
    unique_id: temperature_alert
    icon: >
      {% if is_state('binary_sensor.weather_high_temperature_alert','on') %} mdi:thermometer-alert
      {% elif is_state('binary_sensor.weather_low_temperature_alert','on') %} mdi:thermometer-alert
      {% else %} mdi:thermometer
      {% endif %}
    state: >
      {{ is_state('binary_sensor.weather_high_temperature_alert','on')
          or is_state('binary_sensor.weather_low_temperature_alert','on') }}
    attributes:
      category: weather_alert
      type: >
        {% if is_state('binary_sensor.weather_high_temperature_alert','on') %} Heat
        {% elif is_state('binary_sensor.weather_low_temperature_alert','on') %} Cold
        {% else %} Off
        {% endif %}

  - name: "[Weather] Storm Approaching Alert"
    unique_id: weather_storm_approaching_alert
    icon: mdi:weather-lightning-rainy
    delay_off: "{{ iif(now() - states('sensor.ha_uptime_hours')|as_datetime < timedelta(minutes=5),0,14400) }}"
    state: >
      {{ states('sensor.weather_precipitation_probability')|int >= 30
          and states('sensor.weather_nearest_storm_distance')|int < 5
          and is_state('input_boolean.alerts_weather','on') }}
    availability: >
      {{ is_number(states('sensor.weather_precipitation_probability'))
          and is_number(states('sensor.weather_nearest_storm_distance')) }}

  - name: "[Weather] Lightning Alert"
    unique_id: weather_lightning_alert
    delay_on: 30
    delay_off: 30
    state: >
      {{states('sensor.weather_lightning_count') | int > 0
        and states('sensor.weatherflow_last_lightning_strike_distance') | int < 10
        and is_state('input_boolean.alerts_weather','on') }}
    availability: "{{ is_number(states('sensor.weather_lightning_count')) }}"
    attributes:
      category: weather_alert

  - name: "[Weather] Rain Soon (12Hr Lookahead)"
    unique_id: weather_rain_soon
    icon: mdi:weather-pouring
    state: >
      {% set found = namespace(value=0) %}
      {% if is_state('sensor.weather_precipitation_type','rain') %}
        {% set threshold = 25 %}
        {% set forecast = state_attr('weather.tempest_hourly','forecast') %}
        {% for item in forecast %}
          {% if loop.index0 < 12 and item.precipitation_probability|int(-1) >= threshold %}
            {% set found.value = 1 %}
          {% endif %}
        {% endfor %}
      {% endif %}
      {{ found.value == 1 }}
    availability: >
      {{ state_attr('weather.tempest_hourly','forecast') != none
          and state_attr('weather.tempest_hourly','forecast')[0] is defined }}
