---
substitutions:
  name: switchmonusb_02

esphome:
  name: ${name}
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${name}

captive_portal:

logger:

web_server:
  port: 80

api:
  password: !secret api_password

ota:
  password: !secret ota_password

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
      inverted: true
    name: ${name}_Power_Button
    on_press:
      - switch.toggle: relay

  - platform: status
    name: ${name} Status

switch:
  - platform: gpio
    id: led
    name: ${name}_LED_Green
    pin:
      number: GPIO13
      inverted: true

  - platform: gpio
    name: ${name}_Relay
    pin: GPIO14
    id: relay
    icon: mdi:toggle-switch
    restore_mode: ALWAYS_ON

time:
  - platform: homeassistant
    id: homeassistant_time

sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: true
    cf_pin: GPIO4
    cf1_pin: GPIO5
    current:
      name: ${name}_Current
      unit_of_measurement: A
    voltage:
      name: ${name}_Voltage
      unit_of_measurement: V
    power:
      id: ${name}_wattage
      name: ${name}_Wattage
      unit_of_measurement: W
    ### HIGHER VALUE GIVES LOWER WATTAGE
    current_resistor: 0.00215
    ### LOWER VALUE GIVES LOWER VOLTAGE
    voltage_divider: 799
    change_mode_every: 8
    update_interval: 60s
  - platform: total_daily_energy
    name: ${name}_Daily_Energy
    power_id: ${name}_wattage
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
  - platform: uptime
    name: ${name}_Uptime
  - platform: wifi_signal
    name: ${name}_WiFi_Signal
    update_interval: 60s
