---
trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    hours: "/6"
  - platform: calendar
    event: end
    entity_id: calendar.ical_manchester_united_women
  - platform: event
    event_type: event_template_reloaded
action:
  - service: script.get_calendar
    data:
      entity_id: calendar.ical_manchester_united_women
    response_variable: agenda
  - variables:
      all_events: "{{ agenda.events | list }}"
      next_5_events: "{{ agenda.events[:5] | list }}"
      dump: "{{agenda}}"
      countnumb: "{{agenda.events | count}}"
      lastevent: "{{agenda.events[-1]}}"
sensor:
  - name: "[Upcoming Sport] Manchester United (Women)"
    unique_id: upcoming_sport_manchester_united_women
    icon: "mdi:soccer"
    picture: /local/sportlogos/manchester_united.png
    state: >
      {%- if countnumb == 0 %}
        Nothing Scheduled
      {%- else %}
        {%- from 'easy_time.jinja' import easy_relative_time %}
        {%- set tmpdate = as_timestamp(next_5_events[0]['start']) %}
        {%- set timeto = (as_timestamp(next_5_events[0]['start'])-as_timestamp(now())) / 86400 %}
        {{next_5_events[0]['summary']}} @ {{next_5_events[0]['location']}} - {{ easy_relative_time(tmpdate, 'day, hour, minute') }} ({{ iif(timeto < 6, tmpdate|timestamp_custom ('%a %H:%M'), tmpdate|timestamp_custom ('%d/%m %H:%M'), "None Recorded")}})
      {%- endif %}
    attributes:
      category: sport
      remaining_events: "{{countnumb}}"
      last_event: "{{lastevent.end}}"
      next_5_events: >
        {%- if countnumb == 0 %}
          No Events
        {%- else %}
          {{next_5_events}}
        {%- endif %}
      nextevent_timeto: >
        {%- if countnumb == 0 %}
          -999
        {%- else %}
          {%- set timeto = (as_timestamp(next_5_events[0]['start'])-as_timestamp(now())) / 86400 %}
          {{ timeto | round (0) }}
        {%- endif %}
      nextevent_desc: >
        {%- if countnumb == 0 %}
          No Event Scheduled
        {%- else %}
          {{next_5_events[0]['summary'].split(' - ')[0]}}
        {%- endif %}
      nextevent_locn: >
        {%- if countnumb == 0 %}
          No Event Scheduled
        {%- else %}
          {{next_5_events[0]['location']}}
        {%- endif %}
      nextevent_time: >
        {%- if countnumb == 0 %}
          No Event Scheduled
        {%- else %}
          {%- from 'easy_time.jinja' import easy_relative_time %}
          {%- set tmpdate = as_timestamp(next_5_events[0]['start']) %}
          {%- set timeto = (as_timestamp(next_5_events[0]['start'])-as_timestamp(now())) / 86400 %}
          {{ easy_relative_time(tmpdate, 'day, hour, minute') }} ({{ iif(timeto < 6, tmpdate|timestamp_custom ('%a %H:%M'), tmpdate|timestamp_custom ('%d/%m %H:%M'), "None Recorded")}})
        {%- endif %}
      afterevent_timeto: >
        {%- if countnumb == 0 or countnumb == 1 %}
          -999
        {%- else %}
          {%- set timeto = (as_timestamp(next_5_events[1]['start'])-as_timestamp(now())) / 86400 %}
          {{ timeto | round (0) }}
        {%- endif %}
      afterevent_desc: >
        {%- if countnumb == 0 or countnumb == 1 %}
          No Event Scheduled
        {%- else %}
          {{next_5_events[1]['summary'].split(' - ')[0]}}
        {%- endif %}
      afterevent_locn: >
        {%- if countnumb == 0 or countnumb == 1 %}
          No Event Scheduled
        {%- else %}
          {{next_5_events[1]['location']}}
        {%- endif %}
      afterevent_time: >
        {%- if countnumb == 0 or countnumb == 1 %}
          No Event Scheduled
        {%- else %}
          {%- from 'easy_time.jinja' import easy_relative_time %}
          {%- set tmpdate = as_timestamp(next_5_events[1]['start']) %}
          {%- set timeto = (as_timestamp(next_5_events[1]['start'])-as_timestamp(now())) / 86400 %}
          {{ easy_relative_time(tmpdate, 'day, hour, minute') }} ({{ iif(timeto < 6, tmpdate|timestamp_custom ('%a %H:%M'), tmpdate|timestamp_custom ('%d/%m %H:%M'), "None Recorded")}})
        {%- endif %}
