---
sensor:
  # Chaffey Dam
  - platform: waternsw
    name: Chaffey Dam Volume
    site_id: 419069
    from_variable: 130.00
    to_variable: 136.00
    unit_of_measure: ML
  - platform: waternsw
    name: Chaffey Dam Water Level
    site_id: 419069
    from_variable: 130.00
    to_variable: 130.00
    unit_of_measure: m
  - platform: waternsw
    name: Chaffey Dam Storage
    site_id: 419069
    from_variable: 130.00
    to_variable: 448.00
    unit_of_measure: "%"
  - platform: waternsw
    name: Chaffey Dam Rainfall
    site_id: 419069
    from_variable: 10.00
    to_variable: 10.00
    unit_of_measure: mm
  - platform: waternsw
    name: "Chaffey Dam Net Inflow (24hrs)"
    site_id: 419069
    from_variable: 422.00
    to_variable: 422.00
    unit_of_measure: ML
  - platform: waternsw
    name: "Chaffey Dam Releases (24hrs)"
    site_id: 419069
    from_variable: 459.00
    to_variable: 459.00
    unit_of_measure: ML
  - platform: waternsw
    name: "Chaffey Dam Evaporation (24hrs)"
    site_id: 419069
    from_variable: 700.00
    to_variable: 700.00
    unit_of_measure: mm

  # Keepit Dam
  - platform: waternsw
    name: Keepit Dam Volume
    site_id: 419041
    from_variable: 130.00
    to_variable: 136.00
    unit_of_measure: ML
  - platform: waternsw
    name: Keepit Dam Water Level
    site_id: 419041
    from_variable: 130.00
    to_variable: 130.00
    unit_of_measure: m
  - platform: waternsw
    name: Keepit Dam Storage
    site_id: 419041
    from_variable: 130.00
    to_variable: 448.00
    unit_of_measure: "%"
  - platform: waternsw
    name: Keepit Dam Rainfall
    site_id: 419041
    from_variable: 10.00
    to_variable: 10.00
    unit_of_measure: mm
  - platform: waternsw
    name: "Keepit Dam Net Inflow (24hrs)"
    site_id: 419041
    from_variable: 422.00
    to_variable: 422.00
    unit_of_measure: ML
  - platform: waternsw
    name: "Keepit Dam Releases (24hrs)"
    site_id: 419041
    from_variable: 459.00
    to_variable: 459.00
    unit_of_measure: ML
  - platform: waternsw
    name: "Keepit Dam Evaporation (24hrs)"
    site_id: 419041
    from_variable: 700.00
    to_variable: 700.00
    unit_of_measure: mm

  # Split Rock Dam
  - platform: waternsw
    name: Split Rock Dam Volume
    site_id: 419080
    from_variable: 130.00
    to_variable: 136.00
    unit_of_measure: ML
  - platform: waternsw
    name: Split Rock Dam Water Level
    site_id: 419080
    from_variable: 130.00
    to_variable: 130.00
    unit_of_measure: m
  - platform: waternsw
    name: Split Rock Dam Storage
    site_id: 419080
    from_variable: 130.00
    to_variable: 448.00
    unit_of_measure: "%"
  - platform: waternsw
    name: Split Rock Dam Rainfall
    site_id: 419080
    from_variable: 10.00
    to_variable: 10.00
    unit_of_measure: mm
  - platform: waternsw
    name: "Split Rock Dam Net Inflow (24hrs)"
    site_id: 419080
    from_variable: 422.00
    to_variable: 422.00
    unit_of_measure: ML
  - platform: waternsw
    name: "Split Rock Dam Releases (24hrs)"
    site_id: 419080
    from_variable: 459.00
    to_variable: 459.00
    unit_of_measure: ML
  - platform: waternsw
    name: "Split Rock Dam Evaporation (24hrs)"
    site_id: 419080
    from_variable: 700.00
    to_variable: 700.00
    unit_of_measure: mm

  - platform: template
    sensors:
      waternsw_chaffey_dam:
        friendly_name: "Chaffey Dam"
        icon_template: "mdi:water"
        value_template: "419069"
        attribute_templates:
          dead_water_level: "518.649"
          spillway_level: "525.100"
          catchment_area: "406 sq km"
          surface_area: "542 ha"
          capacity: "102000"
          active_storage: "90360"
          dead_storage: "2400"
          latitude: "-31.348147000"
          longitude: "151.13947000"

      waternsw_keepit_dam:
        friendly_name: "Keepit Dam"
        icon_template: "mdi:water"
        value_template: "419041"
        attribute_templates:
          dead_water_level: "304.570"
          spillway_level: "318.590"
          catchment_area: "5700 sq km"
          surface_area: "4370 ha"
          capacity: "420000"
          active_storage: "243451"
          dead_storage: "6600"
          latitude: "-30.879200000"
          longitude: "150.49280000"

      waternsw_split_rock_dam:
        friendly_name: "Split Rock Dam"
        icon_template: "mdi:water"
        value_template: "419080"
        attribute_templates:
          dead_water_level: "408.000"
          spillway_level: "449.000"
          catchment_area: "1660 sq km"
          surface_area: "2150 ha"
          capacity: "397000"
          active_storage: "116461"
          dead_storage: "3200"
          latitude: "-30.533333333"
          longitude: "150.70000000"
